from _typeshed import Incomplete
from office365.runtime.client_value_collection import (
    ClientValueCollection as ClientValueCollection,
)
from office365.sharepoint.changes.change import Change as Change
from office365.sharepoint.contenttypes.content_type_id import (
    ContentTypeId as ContentTypeId,
)
from office365.sharepoint.sharing.shared_with_user import (
    SharedWithUser as SharedWithUser,
)

class ChangeItem(Change):
    @property
    def activity_type(self) -> str | None: ...
    @property
    def content_type_id(self): ...
    @property
    def editor(self): ...
    @property
    def editor_email_hint(self): ...
    @property
    def editor_login_name(self): ...
    @property
    def file_type(self) -> str | None: ...
    @property
    def item_id(self) -> int | None: ...
    @property
    def is_recycle_bin_operation(self) -> bool | None: ...
    @property
    def server_relative_url(self) -> str | None: ...
    @property
    def shared_by_user(self): ...
    @property
    def shared_with_users(self): ...
    @property
    def unique_id(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
