from _typeshed import Incomplete
from office365.directory.authentication.methods.root import AuthenticationMethodsRoot as AuthenticationMethodsRoot
from office365.entity import Entity as Entity
from office365.partners.partners import Partners as Partners
from office365.reports.internal.queries.create_report_query import create_report_query as create_report_query
from office365.reports.report import Report as Report
from office365.reports.security.root import SecurityReportsRoot as SecurityReportsRoot
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.function import FunctionQuery as FunctionQuery

class ReportRoot(Entity):
    def device_configuration_device_activity(self): ...
    def device_configuration_user_activity(self): ...
    def managed_device_enrollment_failure_details(self): ...
    def managed_device_enrollment_top_failures(self, period: Incomplete | None = None): ...
    def get_email_activity_counts(self, period): ...
    def get_email_activity_user_counts(self, period): ...
    def get_email_activity_user_detail(self, period): ...
    def get_email_app_usage_apps_user_counts(self, period): ...
    def get_email_app_usage_user_counts(self, period): ...
    def get_email_app_usage_user_detail(self, period): ...
    def get_mailbox_usage_storage(self, period): ...
    def get_m365_app_user_counts(self, period: Incomplete | None = None): ...
    def get_office365_activation_counts(self): ...
    def get_office365_activations_user_counts(self): ...
    def get_onedrive_activity_file_counts(self, period): ...
    def get_onedrive_activity_user_counts(self, period): ...
    def get_onedrive_activity_user_detail(self, period): ...
    def get_onedrive_usage_file_counts(self, period): ...
    def get_onedrive_usage_storage(self, period): ...
    def get_mailbox_usage_detail(self, period): ...
    def get_mailbox_usage_mailbox_counts(self, period): ...
    def get_mailbox_usage_quota_status_mailbox_counts(self, period): ...
    def get_sharepoint_activity_pages(self, period): ...
    def get_sharepoint_activity_user_counts(self, period): ...
    def get_sharepoint_activity_user_detail(self, period): ...
    def get_sharepoint_site_usage_detail(self, period): ...
    def get_sharepoint_site_usage_site_counts(self, period): ...
    def get_teams_team_counts(self, period): ...
    @property
    def authentication_methods(self): ...
    @property
    def partners(self): ...
    @property
    def security(self): ...
