from office365.entity import Entity as Entity

class OAuth2PermissionGrant(Entity):
    @property
    def client_id(self) -> str | None: ...
    @property
    def consent_type(self) -> str | None: ...
    @property
    def principal_id(self) -> str | None: ...
    @property
    def resource_id(self) -> str | None: ...
    @property
    def scope(self) -> str | None: ...
