from office365.directory.object import DirectoryObject as DirectoryObject

class ResourceSpecificPermissionGrant(DirectoryObject):
    @property
    def client_id(self) -> str | None: ...
    @property
    def client_app_id(self) -> str | None: ...
    @property
    def permission(self) -> str | None: ...
    @property
    def permission_type(self) -> str | None: ...
    @property
    def resource_app_id(self) -> str | None: ...
