from office365.sharepoint.entity import Entity as Entity

class UserCustomAction(Entity):
    @property
    def client_side_component_id(self) -> str | None: ...
    @property
    def script_block(self) -> str | None: ...
    @script_block.setter
    def script_block(self, value: str) -> None: ...
    @property
    def script_src(self) -> str | None: ...
    @script_src.setter
    def script_src(self, value: str) -> None: ...
    @property
    def url(self) -> str | None: ...
