from _typeshed import Incomplete
from office365.runtime.client_value import ClientValue as ClientValue

class AttachmentCreationInformation(ClientValue):
    def __init__(self, filename: Incomplete | None = None, content: Incomplete | None = None) -> None: ...
    @property
    def content(self): ...
    @content.setter
    def content(self, value) -> None: ...
    @property
    def filename(self): ...
    @filename.setter
    def filename(self, value) -> None: ...
