from office365.runtime.auth.authentication_context import (
    AuthenticationContext as AuthenticationContext,
)
from office365.runtime.auth.client_credential import (
    ClientCredential as ClientCredential,
)
from office365.runtime.auth.token_response import TokenResponse as TokenResponse
from office365.runtime.auth.user_credential import UserCredential as UserCredential
from office365.runtime.client_object import ClientObject as ClientObject
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.client_runtime_context import (
    ClientRuntimeContext as ClientRuntimeContext,
)
from office365.runtime.compat import (
    get_absolute_url as get_absolute_url,
    urlparse as urlparse,
)
from office365.runtime.http.http_method import HttpMethod as HttpMethod
from office365.runtime.http.request_options import RequestOptions as RequestOptions
from office365.runtime.odata.request import ODataRequest as ODataRequest
from office365.runtime.odata.v3.batch_request import (
    ODataBatchV3Request as ODataBatchV3Request,
)
from office365.runtime.odata.v3.json_light_format import (
    JsonLightFormat as JsonLightFormat,
)
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.delete_entity import (
    DeleteEntityQuery as DeleteEntityQuery,
)
from office365.runtime.queries.update_entity import (
    UpdateEntityQuery as UpdateEntityQuery,
)
from office365.runtime.types.event_handler import EventHandler as EventHandler
from office365.sharepoint.portal.groups.site_info import GroupSiteInfo as GroupSiteInfo
from office365.sharepoint.portal.sites.creation_response import (
    SPSiteCreationResponse as SPSiteCreationResponse,
)
from office365.sharepoint.portal.sites.status import SiteStatus as SiteStatus
from office365.sharepoint.principal.users.user import User as User
from office365.sharepoint.publishing.pages.service import (
    SitePageService as SitePageService,
)
from office365.sharepoint.publishing.sites.communication.creation_response import (
    CommunicationSiteCreationResponse as CommunicationSiteCreationResponse,
)
from office365.sharepoint.request_user_context import (
    RequestUserContext as RequestUserContext,
)
from office365.sharepoint.sites.site import Site as Site
from office365.sharepoint.tenant.administration.hubsites.collection import (
    HubSiteCollection as HubSiteCollection,
)
from office365.sharepoint.webs.context_web_information import (
    ContextWebInformation as ContextWebInformation,
)
from office365.sharepoint.webs.web import Web as Web
from typing import Callable
from typing_extensions import Self

class ClientContext(ClientRuntimeContext):
    def __init__(
        self,
        base_url: str,
        auth_context: AuthenticationContext | None = None,
        environment: str = None,
        allow_ntlm: bool = False,
        browser_mode: bool = False,
    ) -> None: ...
    @staticmethod
    def from_url(full_url: str) -> ClientContext: ...
    def with_client_certificate(
        self,
        tenant: str,
        client_id: str,
        thumbprint: str,
        cert_path: str | None = None,
        private_key: str | None = None,
        scopes: list[str] | None = None,
        passphrase: str | None = None,
    ) -> Self: ...
    def with_interactive(
        self, tenant: str, client_id: str, scopes: list[str] | None = None
    ) -> Self: ...
    def with_device_flow(
        self, tenant: str, client_id: str, scopes: list[str] | None = None
    ) -> Self: ...
    def with_access_token(self, token_func: Callable[[], TokenResponse]) -> Self: ...
    def with_user_credentials(self, username: str, password: str) -> Self: ...
    def with_client_credentials(self, client_id: str, client_secret: str) -> Self: ...
    def with_credentials(
        self, credentials: UserCredential | ClientCredential
    ) -> Self: ...
    def execute_batch(
        self,
        items_per_batch: int = 100,
        success_callback: Callable[[list[ClientObject | ClientResult]], None] = None,
    ) -> Self: ...
    def pending_request(self): ...
    def execute_query_with_incremental_retry(self, max_retry: int = 5) -> None: ...
    def clone(self, url, clear_queries: bool = True): ...
    def create_modern_site(
        self, title: str, alias: str, owner: str | User | None = None
    ) -> Site: ...
    def create_team_site(self, alias, title, is_public: bool = True): ...
    def create_communication_site(self, alias, title): ...
    @property
    def context_info(self): ...
    @property
    def web(self): ...
    @property
    def site(self): ...
    @property
    def apps(self): ...
    @property
    def announcements(self): ...
    @property
    def brand_center(self): ...
    @property
    def client_people_picker(self): ...
    @property
    def component_context_info(self): ...
    @property
    def consumer_permissions(self): ...
    @property
    def me(self): ...
    @property
    def ee(self): ...
    @property
    def directory_provider(self): ...
    @property
    def employee_experience(self): ...
    @property
    def micro_service_manager(self): ...
    @property
    def directory_session(self): ...
    @property
    def models(self): ...
    @property
    def folder_coloring(self): ...
    @property
    def font_packages(self): ...
    @property
    def site_font_packages(self): ...
    @property
    def group_site_manager(self): ...
    @property
    def group_service(self): ...
    @property
    def navigation_service(self): ...
    @property
    def page_diagnostics(self): ...
    @property
    def people_manager(self): ...
    @property
    def profile_loader(self): ...
    @property
    def document_crawl_log(self): ...
    @property
    def lists(self): ...
    @property
    def hub_sites(self): ...
    @property
    def hub_sites_utility(self): ...
    @property
    def machine_learning(self): ...
    @property
    def org_news(self): ...
    @property
    def org_news_site(self): ...
    @property
    def search_setting(self): ...
    @property
    def site_pages(self): ...
    @property
    def site_icon_manager(self): ...
    @property
    def site_linking_manager(self): ...
    @property
    def site_manager(self): ...
    @property
    def site_manager_svc(self): ...
    @property
    def social_feed_manager(self): ...
    @property
    def home_service(self): ...
    @property
    def home_site(self): ...
    @property
    def people_picker(self): ...
    @property
    def publications(self): ...
    @property
    def server_settings(self): ...
    @property
    def social_following_manager(self): ...
    @property
    def theme_manager(self): ...
    @property
    def taxonomy(self): ...
    @property
    def search(self): ...
    @property
    def tenant_settings(self): ...
    @property
    def viva_site_manager(self): ...
    @property
    def workflow_services_manager(self): ...
    @property
    def workflow_deployment_service(self): ...
    @property
    def work_items(self): ...
    @property
    def tenant(self): ...
    @property
    def tenant_url(self): ...
    @property
    def site_path(self): ...
    @property
    def is_tenant(self): ...
    @property
    def base_url(self): ...
    @property
    def authentication_context(self): ...
    def service_root_url(self): ...
