from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.client_context import ClientContext as ClientContext
from office365.sharepoint.entity import Entity as Entity

class TenantCrawlVersionsInfoProvider(Entity):
    @staticmethod
    def create(context: ClientContext) -> TenantCrawlVersionsInfoProvider: ...
    def disable_crawl_versions(self, site_id): ...
    def is_crawl_versions_enabled(self, site_id): ...
    def is_crawl_versions_enabled_for_tenant(self): ...
    @property
    def entity_type_name(self): ...
