from ... import errors as errors
from ...client import AuthenticatedClient as AuthenticatedClient
from ...client import Client as Client
from ...models.qualer_api_models_asset_to_assets_count_response_model import (
    QualerApiModelsAssetToAssetsCountResponseModel as QualerApiModelsAssetToAssetsCountResponseModel,
)
from ...types import UNSET as UNSET
from ...types import Response as Response
from ...types import Unset as Unset

def sync_detailed(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> Response[QualerApiModelsAssetToAssetsCountResponseModel]: ...
def sync(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> QualerApiModelsAssetToAssetsCountResponseModel | None: ...
async def asyncio_detailed(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> Response[QualerApiModelsAssetToAssetsCountResponseModel]: ...
async def asyncio(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> QualerApiModelsAssetToAssetsCountResponseModel | None: ...
