from _typeshed import Incomplete
from datetime import datetime
from office365.directory.permissions.identity_set import IdentitySet as IdentitySet
from office365.entity import Entity as Entity
from office365.onedrive.listitems.item_reference import ItemReference as ItemReference
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class BaseItem(Entity):
    @property
    def etag(self) -> str | None: ...
    @property
    def created_by(self) -> IdentitySet: ...
    @property
    def created_by_user(self): ...
    @property
    def last_modified_by(self) -> IdentitySet: ...
    @property
    def last_modified_by_user(self): ...
    @property
    def created_datetime(self) -> datetime | None: ...
    @property
    def last_modified_datetime(self) -> datetime | None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def description(self) -> str | None: ...
    @description.setter
    def description(self, value: str) -> None: ...
    @property
    def web_url(self) -> str | None: ...
    @property
    def parent_reference(self) -> ItemReference: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
