import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar(
    "T",
    bound="QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModelMeasurementSetResponseModelMeasurementPointResponseModelMeasurementResponseModel",
)

@_attrs_define
class QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModelMeasurementSetResponseModelMeasurementPointResponseModelMeasurementResponseModel:
    values: Unset | str = ...
    mean: Unset | float = ...
    sd: Unset | float = ...
    range_: Unset | float = ...
    delta: Unset | float = ...
    cv: Unset | float = ...
    cmc: Unset | float = ...
    mu: Unset | float = ...
    tur: Unset | float = ...
    tar: Unset | float = ...
    max_value: Unset | float = ...
    min_value: Unset | float = ...
    error: Unset | float = ...
    result: Unset | str = ...
    updated_on: Unset | datetime.datetime = ...
    updated_by: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
