from pydantic import BaseModel, StrictBool as StrictBool, StrictStr as StrictStr

class QualerWebMvcAreasApiModelsAccountToLoginModel(BaseModel):
    user_name: StrictStr
    password: StrictStr
    clear_previous_tokens: StrictBool | None
    class Config:
        allow_population_by_field_name: bool
        validate_assignment: bool
    def to_str(self) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str) -> QualerWebMvcAreasApiModelsAccountToLoginModel: ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, obj: dict) -> QualerWebMvcAreasApiModelsAccountToLoginModel: ...
