from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_measurements_from_create_measurement_point_model import (
    QualerApiModelsMeasurementsFromCreateMeasurementPointModel as QualerApiModelsMeasurementsFromCreateMeasurementPointModel,
)
from ..models.qualer_api_models_measurements_from_custom_fields import (
    QualerApiModelsMeasurementsFromCustomFields as QualerApiModelsMeasurementsFromCustomFields,
)
from ..models.qualer_api_models_measurements_from_display_options import (
    QualerApiModelsMeasurementsFromDisplayOptions as QualerApiModelsMeasurementsFromDisplayOptions,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsMeasurementsFromCreateMeasurementSetModel")

@_attrs_define
class QualerApiModelsMeasurementsFromCreateMeasurementSetModel:
    measurement_name: Unset | str = ...
    is_accredited: Unset | bool = ...
    measurement_quantity_id: Unset | int = ...
    default_unit_of_measure_id: Unset | int = ...
    decimal_places: Unset | int = ...
    significant_figures: Unset | int = ...
    display_options: Unset | QualerApiModelsMeasurementsFromDisplayOptions = ...
    custom_fields: Unset | QualerApiModelsMeasurementsFromCustomFields = ...
    measurement_points: (
        Unset | list["QualerApiModelsMeasurementsFromCreateMeasurementPointModel"]
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
