import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_asset_to_asset_service_forecast_model_on_day import (
    QualerApiModelsAssetToAssetServiceForecastModelOnDay as QualerApiModelsAssetToAssetServiceForecastModelOnDay,
)
from ..models.qualer_api_models_asset_to_asset_service_forecast_model_on_month import (
    QualerApiModelsAssetToAssetServiceForecastModelOnMonth as QualerApiModelsAssetToAssetServiceForecastModelOnMonth,
)
from ..models.qualer_api_models_asset_to_asset_service_forecast_model_on_week_days import (
    QualerApiModelsAssetToAssetServiceForecastModelOnWeekDays as QualerApiModelsAssetToAssetServiceForecastModelOnWeekDays,
)
from ..models.qualer_api_models_asset_to_asset_service_forecast_model_weekday_of_month import (
    QualerApiModelsAssetToAssetServiceForecastModelWeekdayOfMonth as QualerApiModelsAssetToAssetServiceForecastModelWeekdayOfMonth,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsAssetToAssetServiceForecastModel")

@_attrs_define
class QualerApiModelsAssetToAssetServiceForecastModel:
    company_id: Unset | int = ...
    asset_id: Unset | int = ...
    site_id: Unset | int = ...
    asset_service_record_id: Unset | int = ...
    serial_number: Unset | str = ...
    asset_user: Unset | str = ...
    asset_tag: Unset | str = ...
    equipment_id: Unset | str = ...
    asset_name: Unset | str = ...
    category_name: Unset | str = ...
    manufacturer_name: Unset | str = ...
    site_name: Unset | str = ...
    maintenance_plan_id: Unset | int = ...
    maintenance_plan_name: Unset | str = ...
    maintenance_task_id: Unset | int = ...
    maintenance_task_name: Unset | str = ...
    next_service_date: Unset | datetime.datetime = ...
    advance_recall_date: Unset | datetime.datetime = ...
    grace_period_date: Unset | datetime.datetime = ...
    certificate_next_service_date: Unset | datetime.datetime = ...
    service_interval: Unset | str = ...
    interval_cycle: Unset | str = ...
    interval_length: Unset | int = ...
    on_day: Unset | QualerApiModelsAssetToAssetServiceForecastModelOnDay = ...
    on_month: Unset | QualerApiModelsAssetToAssetServiceForecastModelOnMonth = ...
    on_week_days: Unset | QualerApiModelsAssetToAssetServiceForecastModelOnWeekDays = (
        ...
    )
    weekday_of_month: (
        Unset | QualerApiModelsAssetToAssetServiceForecastModelWeekdayOfMonth
    ) = ...
    advance_recall_period: Unset | str = ...
    days_before_due: Unset | int = ...
    past_due_grace_period: Unset | str = ...
    days_after_due: Unset | int = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
