from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_measurements_from_create_measurement_condition_factor_model import (
    QualerApiModelsMeasurementsFromCreateMeasurementConditionFactorModel as QualerApiModelsMeasurementsFromCreateMeasurementConditionFactorModel,
)
from ..models.qualer_api_models_measurements_from_create_measurement_model import (
    QualerApiModelsMeasurementsFromCreateMeasurementModel as QualerApiModelsMeasurementsFromCreateMeasurementModel,
)
from ..models.qualer_api_models_measurements_from_create_measurement_tool_model import (
    QualerApiModelsMeasurementsFromCreateMeasurementToolModel as QualerApiModelsMeasurementsFromCreateMeasurementToolModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsMeasurementsFromCreateMeasurementPointModel")

@_attrs_define
class QualerApiModelsMeasurementsFromCreateMeasurementPointModel:
    specification_name: Unset | str = ...
    measurement_quantity: Unset | str = ...
    unit_of_measure_id: Unset | int = ...
    unit_of_measure: Unset | str = ...
    range_min: Unset | float = ...
    range_max: Unset | float = ...
    specification_mode: Unset | str = ...
    tolerance_type: Unset | str = ...
    tolerance_mode: Unset | str = ...
    tolerance_unit: Unset | str = ...
    precision_type: Unset | str = ...
    readings: Unset | int = ...
    channels_type: Unset | str = ...
    channel_count: Unset | int = ...
    precision: Unset | float = ...
    tolerance_minimum: Unset | float = ...
    tolerance_maximum: Unset | float = ...
    resolution: Unset | float = ...
    resolution_count: Unset | float = ...
    nominal: Unset | float = ...
    expected_value: Unset | float = ...
    base_value: Unset | float = ...
    test_value: Unset | float = ...
    is_accredited: Unset | bool = ...
    measurements: (
        Unset | list["QualerApiModelsMeasurementsFromCreateMeasurementModel"]
    ) = ...
    condition_factors: (
        Unset
        | list["QualerApiModelsMeasurementsFromCreateMeasurementConditionFactorModel"]
    ) = ...
    primary_measurement_tool: (
        Unset | QualerApiModelsMeasurementsFromCreateMeasurementToolModel
    ) = ...
    secondary_measurement_tool: (
        Unset | QualerApiModelsMeasurementsFromCreateMeasurementToolModel
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
