import datetime
from collections.abc import Mapping
from typing import Any, TypeVar
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_address_to_address_response_model import (
    QualerApiModelsAddressToAddressResponseModel as QualerApiModelsAddressToAddressResponseModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsServiceOrdersToClientOrderResponseModel")

@_attrs_define
class QualerApiModelsServiceOrdersToClientOrderResponseModel:
    service_order_id: Unset | int = ...
    parent_order_id: Unset | int = ...
    client_legacy_id: Unset | str = ...
    owner_name: Unset | str = ...
    submited_by_name: Unset | str = ...
    sign_off_by_name: Unset | str = ...
    vendor_sign_off_by_name: Unset | str = ...
    approved_by_name: Unset | str = ...
    accepted_by_name: Unset | str = ...
    ready_for_quality_control_by_name: Unset | str = ...
    quality_control_by_name: Unset | str = ...
    created_by_name: Unset | str = ...
    completed_by_name: Unset | str = ...
    shipped_by_name: Unset | str = ...
    delivered_by_name: Unset | str = ...
    invoiced_by_name: Unset | str = ...
    paid_by_name: Unset | str = ...
    cancelled_by_name: Unset | str = ...
    closed_by_name: Unset | str = ...
    client_company_id: Unset | int = ...
    client_company_name: Unset | str = ...
    client_domain_name: Unset | str = ...
    client_alternative_names: Unset | str = ...
    service_comments: Unset | str = ...
    service_private_comments: Unset | str = ...
    created_on: Unset | datetime.datetime = ...
    approved_on: Unset | datetime.datetime = ...
    sign_off_on: Unset | datetime.datetime = ...
    vendor_sign_off_on: Unset | datetime.datetime = ...
    completed_on: Unset | datetime.datetime = ...
    submited_on: Unset | datetime.datetime = ...
    shipped_on: Unset | datetime.datetime = ...
    accepted_on: Unset | datetime.datetime = ...
    ready_for_quality_control_on: Unset | datetime.datetime = ...
    quality_control_on: Unset | datetime.datetime = ...
    delivered_on: Unset | datetime.datetime = ...
    invoiced_on: Unset | datetime.datetime = ...
    last_invoiced_on: Unset | datetime.datetime = ...
    payment_due_on: Unset | datetime.datetime = ...
    paid_on: Unset | datetime.datetime = ...
    late_fee_on: Unset | datetime.datetime = ...
    cancelled_on: Unset | datetime.datetime = ...
    closed_on: Unset | datetime.datetime = ...
    last_updated_on: Unset | datetime.datetime = ...
    last_updated_by: Unset | str = ...
    submited_by_id: Unset | int = ...
    sign_off_by_id: Unset | int = ...
    vendor_sign_off_by_id: Unset | int = ...
    approved_by_id: Unset | int = ...
    late_fee_by_id: Unset | int = ...
    accepted_by_id: Unset | int = ...
    ready_for_quality_control_by_id: Unset | int = ...
    quality_control_by_id: Unset | int = ...
    created_by_id: Unset | int = ...
    completed_by_id: Unset | int = ...
    shipped_by_id: Unset | int = ...
    delivered_by_id: Unset | int = ...
    invoiced_by_id: Unset | int = ...
    paid_by_id: Unset | int = ...
    cancelled_by_id: Unset | int = ...
    closed_by_id: Unset | int = ...
    po_number: Unset | str = ...
    secondary_po: Unset | str = ...
    service_total: Unset | float = ...
    repairs_total: Unset | float = ...
    parts_total: Unset | float = ...
    parts_total_before_discount: Unset | float = ...
    parts_discount_total: Unset | float = ...
    effective_tax_rate: Unset | float = ...
    tax_amount: Unset | float = ...
    shipping_fee: Unset | float = ...
    travel_charge: Unset | float = ...
    late_fee: Unset | float = ...
    is_tax_exempt: Unset | bool = ...
    service_discount: Unset | float = ...
    trade_in_credit: Unset | float = ...
    prepaid_credit: Unset | float = ...
    grand_total: Unset | float = ...
    paid_amount: Unset | float = ...
    remaining_balance: Unset | float = ...
    service_discount_details: Unset | str = ...
    trade_in_credit_details: Unset | str = ...
    prepaid_credit_details: Unset | str = ...
    payment_notes: Unset | str = ...
    service_order_number: Unset | int = ...
    legacy_order_number: Unset | str = ...
    custom_order_number: Unset | str = ...
    payment_status: Unset | str = ...
    payment_option: Unset | str = ...
    shipment_status: Unset | str = ...
    order_status: Unset | str = ...
    owner_id: Unset | int = ...
    owner_department: Unset | str = ...
    client_site: Unset | str = ...
    client_site_code: Unset | str = ...
    vendor_site: Unset | str = ...
    internal: Unset | bool = ...
    guid: Unset | UUID = ...
    business_from_time: Unset | datetime.datetime = ...
    business_to_time: Unset | datetime.datetime = ...
    site_access_notes: Unset | str = ...
    desired_date: Unset | datetime.datetime = ...
    deadline_date: Unset | datetime.datetime = ...
    request_from_date: Unset | datetime.datetime = ...
    request_from_time: Unset | datetime.datetime = ...
    request_to_date: Unset | datetime.datetime = ...
    request_to_time: Unset | datetime.datetime = ...
    order_notes: Unset | str = ...
    billing_address: Unset | QualerApiModelsAddressToAddressResponseModel = ...
    shipping_address: Unset | QualerApiModelsAddressToAddressResponseModel = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
