from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_environment_to_environment_model_factor_id import (
    QualerApiModelsEnvironmentToEnvironmentModelFactorId as QualerApiModelsEnvironmentToEnvironmentModelFactorId,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsEnvironmentToEnvironmentModel")

@_attrs_define
class QualerApiModelsEnvironmentToEnvironmentModel:
    room_name: Unset | str = ...
    factor_id: Unset | QualerApiModelsEnvironmentToEnvironmentModelFactorId = ...
    station_id: Unset | int = ...
    factor_name: Unset | str = ...
    factor_value: Unset | float = ...
    valid_range_min: Unset | float = ...
    valid_range_max: Unset | float = ...
    unit_of_measure: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
