from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_measurements_from_update_measurement_condition_factor_model import (
    QualerApiModelsMeasurementsFromUpdateMeasurementConditionFactorModel as QualerApiModelsMeasurementsFromUpdateMeasurementConditionFactorModel,
)
from ..models.qualer_api_models_measurements_from_update_measurement_model import (
    QualerApiModelsMeasurementsFromUpdateMeasurementModel as QualerApiModelsMeasurementsFromUpdateMeasurementModel,
)
from ..models.qualer_api_models_measurements_from_update_measurement_point_model_hysteresis_point import (
    QualerApiModelsMeasurementsFromUpdateMeasurementPointModelHysteresisPoint as QualerApiModelsMeasurementsFromUpdateMeasurementPointModelHysteresisPoint,
)
from ..models.qualer_api_models_measurements_from_update_measurement_point_model_specification_mode import (
    QualerApiModelsMeasurementsFromUpdateMeasurementPointModelSpecificationMode as QualerApiModelsMeasurementsFromUpdateMeasurementPointModelSpecificationMode,
)
from ..models.qualer_api_models_measurements_from_update_measurement_point_model_tolerance_mode import (
    QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToleranceMode as QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToleranceMode,
)
from ..models.qualer_api_models_measurements_from_update_measurement_point_model_tolerance_unit import (
    QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToleranceUnit as QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToleranceUnit,
)
from ..models.qualer_api_models_measurements_from_update_measurement_point_model_tool_application_mode import (
    QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToolApplicationMode as QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToolApplicationMode,
)
from ..models.qualer_api_models_measurements_from_update_measurement_tool_model import (
    QualerApiModelsMeasurementsFromUpdateMeasurementToolModel as QualerApiModelsMeasurementsFromUpdateMeasurementToolModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsMeasurementsFromUpdateMeasurementPointModel")

@_attrs_define
class QualerApiModelsMeasurementsFromUpdateMeasurementPointModel:
    measurement_point_id: Unset | int = ...
    specification_name: Unset | str = ...
    unit_of_measure: Unset | str = ...
    expected_value: Unset | float = ...
    expected_value_raw: Unset | str = ...
    base_value: Unset | float = ...
    test_value: Unset | float = ...
    nominal: Unset | float = ...
    range_min: Unset | float = ...
    range_max: Unset | float = ...
    tolerance_type: Unset | str = ...
    precision_type: Unset | str = ...
    precision: Unset | float = ...
    tolerance_minimum: Unset | float = ...
    tolerance_maximum: Unset | float = ...
    resolution: Unset | float = ...
    resolution_count: Unset | float = ...
    is_accredited: Unset | bool = ...
    specification_mode: (
        Unset
        | QualerApiModelsMeasurementsFromUpdateMeasurementPointModelSpecificationMode
    ) = ...
    tolerance_mode: (
        Unset | QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToleranceMode
    ) = ...
    tolerance_unit: (
        Unset | QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToleranceUnit
    ) = ...
    measurements: (
        Unset | list["QualerApiModelsMeasurementsFromUpdateMeasurementModel"]
    ) = ...
    measurement_condition_factors: (
        Unset
        | list["QualerApiModelsMeasurementsFromUpdateMeasurementConditionFactorModel"]
    ) = ...
    tool_application_mode: (
        Unset
        | QualerApiModelsMeasurementsFromUpdateMeasurementPointModelToolApplicationMode
    ) = ...
    primary_measurement_tool: (
        Unset | QualerApiModelsMeasurementsFromUpdateMeasurementToolModel
    ) = ...
    secondary_measurement_tool: (
        Unset | QualerApiModelsMeasurementsFromUpdateMeasurementToolModel
    ) = ...
    linked_measurement_point_id: Unset | int = ...
    hysteresis_point: (
        Unset
        | QualerApiModelsMeasurementsFromUpdateMeasurementPointModelHysteresisPoint
    ) = ...
    influence_parameter_1_parameter_id: Unset | int = ...
    influence_parameter_1_value: Unset | str = ...
    influence_parameter_2_parameter_id: Unset | int = ...
    influence_parameter_2_value: Unset | str = ...
    measurement_not_taken_reason: Unset | str = ...
    hide_from_certificate: Unset | bool = ...
    measurement_not_taken_result: Unset | str = ...
    is_measurement_not_taken: Unset | bool = ...
    column_mean: Unset | str = ...
    column_mean_result: Unset | str = ...
    column_sd: Unset | str = ...
    column_sd_result: Unset | str = ...
    column_cv: Unset | str = ...
    column_cv_result: Unset | str = ...
    column_range: Unset | str = ...
    column_range_result: Unset | str = ...
    column_delta: Unset | str = ...
    column_delta_result: Unset | str = ...
    column_result: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
