from pydantic import BaseModel, StrictBool as StrictBool, StrictStr as StrictStr

class QualerApiModelsServiceOrderDocumentsFromUploadDocumentsModel(BaseModel):
    report_type: StrictStr | None
    is_private: StrictBool | None
    class Config:
        allow_population_by_field_name: bool
        validate_assignment: bool
    def to_str(self) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str) -> QualerApiModelsServiceOrderDocumentsFromUploadDocumentsModel: ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, obj: dict) -> QualerApiModelsServiceOrderDocumentsFromUploadDocumentsModel: ...
