from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_measurements_from_update_measurement_set_model import (
    QualerApiModelsMeasurementsFromUpdateMeasurementSetModel as QualerApiModelsMeasurementsFromUpdateMeasurementSetModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsMeasurementsFromUpdateMeasurementBatchModel")

@_attrs_define
class QualerApiModelsMeasurementsFromUpdateMeasurementBatchModel:
    batch_id: Unset | int = ...
    batch_type: Unset | str = ...
    save_and_delete_empty: Unset | bool = ...
    measurement_sets: (
        Unset | list["QualerApiModelsMeasurementsFromUpdateMeasurementSetModel"]
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
