import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_address_to_address_response_model import (
    QualerApiModelsAddressToAddressResponseModel as QualerApiModelsAddressToAddressResponseModel,
)
from ..models.qualer_api_models_common_from_attribute_model import (
    QualerApiModelsCommonFromAttributeModel as QualerApiModelsCommonFromAttributeModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsSiteToClientSiteResponse")

@_attrs_define
class QualerApiModelsSiteToClientSiteResponse:
    site_id: Unset | int = ...
    site_name: Unset | str = ...
    site_code: Unset | str = ...
    shipping_address: Unset | QualerApiModelsAddressToAddressResponseModel = ...
    shipping_inherited: Unset | bool = ...
    billing_address: Unset | QualerApiModelsAddressToAddressResponseModel = ...
    default_account_representative_employee_id: Unset | int = ...
    billing_inherited: Unset | bool = ...
    federal_number: Unset | str = ...
    state_number: Unset | str = ...
    culture_name: Unset | str = ...
    is_science_facility: Unset | bool = ...
    is_service_center: Unset | bool = ...
    is_inventory_storage: Unset | bool = ...
    is_production: Unset | bool = ...
    time_zone_id: Unset | str = ...
    time_zone_offset_minutes: Unset | int = ...
    updated_on_utc: Unset | datetime.datetime = ...
    attributes: Unset | list["QualerApiModelsCommonFromAttributeModel"] = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
