import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_measurements_to_measurement_record_response_model_measurement_batch_response_model import (
    QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel as QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsMeasurementsToMeasurementRecordResponseModel")

@_attrs_define
class QualerApiModelsMeasurementsToMeasurementRecordResponseModel:
    service_order_id: Unset | int = ...
    service_order_number: Unset | int = ...
    custom_order_number: Unset | str = ...
    order_item_number: Unset | int = ...
    certificate_number: Unset | str = ...
    result_status: Unset | str = ...
    as_found_result: Unset | str = ...
    as_left_result: Unset | str = ...
    service_date: Unset | datetime.datetime = ...
    serial_number: Unset | str = ...
    asset_tag: Unset | str = ...
    asset_user: Unset | str = ...
    asset_tag_change: Unset | str = ...
    asset_user_change: Unset | str = ...
    service_notes: Unset | str = ...
    serial_number_change: Unset | str = ...
    due_date: Unset | datetime.datetime = ...
    next_service_date: Unset | datetime.datetime = ...
    service_level: Unset | str = ...
    service_level_code: Unset | str = ...
    next_service_level: Unset | str = ...
    next_service_level_code: Unset | str = ...
    asset_name: Unset | str = ...
    asset_description: Unset | str = ...
    parts_charge: Unset | float = ...
    parts_charge_before_discount: Unset | float = ...
    service_charge: Unset | float = ...
    repairs_charge: Unset | float = ...
    segment_name: Unset | str = ...
    schedule_name: Unset | str = ...
    service_schedule_segment_id: Unset | int = ...
    forward_next_service: Unset | bool = ...
    forward_segment_id: Unset | int = ...
    measurement_batches: (
        Unset
        | list[
            "QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel"
        ]
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
