import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_service_options_to_service_option_response_model import (
    QualerApiModelsServiceOptionsToServiceOptionResponseModel as QualerApiModelsServiceOptionsToServiceOptionResponseModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsServiceOrdersToClientOrderItemResponseModel")

@_attrs_define
class QualerApiModelsServiceOrdersToClientOrderItemResponseModel:
    work_item_id: Unset | int = ...
    client_notes: Unset | str = ...
    service_comments: Unset | str = ...
    private_comments: Unset | str = ...
    order_item_number: Unset | int = ...
    service_order_id: Unset | int = ...
    channel_count: Unset | int = ...
    service_total: Unset | float = ...
    repairs_total: Unset | float = ...
    parts_total: Unset | float = ...
    parts_total_before_discount: Unset | float = ...
    override_service_total: Unset | bool = ...
    override_repairs_total: Unset | bool = ...
    override_parts_total: Unset | bool = ...
    service_type: Unset | str = ...
    document_number: Unset | str = ...
    document_section: Unset | str = ...
    work_status: Unset | str = ...
    custom_work_status: Unset | str = ...
    is_limited: Unset | bool = ...
    checked_on: Unset | datetime.datetime = ...
    checked_by_name: Unset | str = ...
    checked_by_id: Unset | int = ...
    completed_on: Unset | datetime.datetime = ...
    completed_by_name: Unset | str = ...
    completed_by_id: Unset | int = ...
    updated_by_id: Unset | int = ...
    updated_by: Unset | str = ...
    as_found_check: Unset | str = ...
    as_left_check: Unset | str = ...
    item_result_status: Unset | str = ...
    item_as_found_result: Unset | str = ...
    item_as_left_result: Unset | str = ...
    as_found_specification: Unset | int = ...
    as_left_specification: Unset | int = ...
    created_on_utc: Unset | datetime.datetime = ...
    updated_on_utc: Unset | datetime.datetime = ...
    equipment_id: Unset | str = ...
    service_level: Unset | str = ...
    service_level_code: Unset | str = ...
    service_level_document_number: Unset | str = ...
    service_level_document_section: Unset | str = ...
    next_service_level: Unset | str = ...
    next_service_level_code: Unset | str = ...
    result_status: Unset | str = ...
    as_found_result: Unset | str = ...
    as_left_result: Unset | str = ...
    serial_number: Unset | str = ...
    serial_number_change: Unset | str = ...
    asset_tag: Unset | str = ...
    asset_user: Unset | str = ...
    asset_tag_change: Unset | str = ...
    asset_user_change: Unset | str = ...
    asset_id: Unset | int = ...
    asset_name: Unset | str = ...
    asset_description: Unset | str = ...
    asset_site_name: Unset | str = ...
    asset_site_id: Unset | int = ...
    asset_company_name: Unset | str = ...
    asset_company_id: Unset | int = ...
    client_company_id: Unset | int = ...
    vendor_company_id: Unset | int = ...
    service_notes: Unset | str = ...
    provider_technician: Unset | str = ...
    provider_phone: Unset | str = ...
    provider_company: Unset | str = ...
    service_charge: Unset | float = ...
    repairs_charge: Unset | float = ...
    parts_charge: Unset | float = ...
    parts_charge_before_discount: Unset | float = ...
    custom_order_number: Unset | str = ...
    certificate_number: Unset | str = ...
    service_date: Unset | datetime.datetime = ...
    due_date: Unset | datetime.datetime = ...
    next_service_date: Unset | datetime.datetime = ...
    maintenance_task: Unset | str = ...
    maintenance_plan: Unset | str = ...
    service_options: (
        Unset | list["QualerApiModelsServiceOptionsToServiceOptionResponseModel"]
    ) = ...
    vendor_tag: Unset | str = ...
    legacy_id: Unset | str = ...
    asset_ownership: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
