from pydantic import BaseModel, conlist as conlist
from qualer_sdk.models.qualer_api_models_measurements_to_update_measurement_batch_response_model import QualerApiModelsMeasurementsToUpdateMeasurementBatchResponseModel as QualerApiModelsMeasurementsToUpdateMeasurementBatchResponseModel

class QualerApiModelsMeasurementsToUpdateMeasurementFormResponseModel(BaseModel):
    measurement_batches: None | None
    class Config:
        allow_population_by_field_name: bool
        validate_assignment: bool
    def to_str(self) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str) -> QualerApiModelsMeasurementsToUpdateMeasurementFormResponseModel: ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, obj: dict) -> QualerApiModelsMeasurementsToUpdateMeasurementFormResponseModel: ...
