from collections.abc import Mapping
from typing import Any, TypeVar
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_service_order_documents_to_company_order_controlled_document_response_document_type import (
    QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponseDocumentType as QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponseDocumentType,
)
from ..models.qualer_api_models_service_order_documents_to_company_order_controlled_document_response_report_type import (
    QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponseReportType as QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponseReportType,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar(
    "T",
    bound="QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponse",
)

@_attrs_define
class QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponse:
    service_order_id: Unset | int = ...
    guid: Unset | UUID = ...
    document_name: Unset | str = ...
    file_name: Unset | str = ...
    document_type: (
        Unset
        | QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponseDocumentType
    ) = ...
    revision_number: Unset | int = ...
    report_type: (
        Unset
        | QualerApiModelsServiceOrderDocumentsToCompanyOrderControlledDocumentResponseReportType
    ) = ...
    download_url: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
