from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_address_address_model import (
    QualerApiModelsAddressAddressModel as QualerApiModelsAddressAddressModel,
)
from ..models.qualer_api_models_clients_from_sponsored_client_edit_model_client_status import (
    QualerApiModelsClientsFromSponsoredClientEditModelClientStatus as QualerApiModelsClientsFromSponsoredClientEditModelClientStatus,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsClientsFromSponsoredClientEditModel")

@_attrs_define
class QualerApiModelsClientsFromSponsoredClientEditModel:
    company_id: Unset | int = ...
    account_number_text: Unset | str = ...
    client_status: (
        Unset | QualerApiModelsClientsFromSponsoredClientEditModelClientStatus
    ) = ...
    domain_name: Unset | str = ...
    custom_client_name: Unset | str = ...
    legacy_id: Unset | str = ...
    currency_id: Unset | int = ...
    account_representative_employee_id: Unset | int = ...
    account_representative_site_id: Unset | int = ...
    account_manager_employee_id: Unset | int = ...
    company_name: Unset | str = ...
    billing_address: Unset | QualerApiModelsAddressAddressModel = ...
    shipping_address: Unset | QualerApiModelsAddressAddressModel = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
