from pydantic import BaseModel, StrictInt as StrictInt, conlist as conlist

class QualerApiModelsServiceOrdersFromAddWorkItemsModel(BaseModel):
    asset_ids: None | None
    schedule_segment_ids: None | None
    class Config:
        allow_population_by_field_name: bool
        validate_assignment: bool
    def to_str(self) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str) -> QualerApiModelsServiceOrdersFromAddWorkItemsModel: ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, obj: dict) -> QualerApiModelsServiceOrdersFromAddWorkItemsModel: ...
