from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar(
    "T", bound="QualerWebMvcAreasApiModelsServicePricesFromServicePriceBulkEditModel"
)

@_attrs_define
class QualerWebMvcAreasApiModelsServicePricesFromServicePriceBulkEditModel:
    service_option_id: Unset | int = ...
    service_option: Unset | str = ...
    service_option_code: Unset | str = ...
    option_type: Unset | str = ...
    description: Unset | str = ...
    service_task_id: Unset | int = ...
    service_code: Unset | str = ...
    document_number: Unset | str = ...
    document_section: Unset | str = ...
    capability_id: Unset | int = ...
    service_type_id: Unset | int = ...
    service_task_price_id: Unset | int = ...
    service_pricing_id: Unset | int = ...
    price: Unset | float = ...
    is_hourly: Unset | bool = ...
    issue: Unset | str = ...
    log_error: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
