from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_service_order_item_parts_to_order_item_part_response_model_service_order_charge_type import (
    QualerApiModelsServiceOrderItemPartsToOrderItemPartResponseModelServiceOrderChargeType as QualerApiModelsServiceOrderItemPartsToOrderItemPartResponseModelServiceOrderChargeType,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar(
    "T", bound="QualerApiModelsServiceOrderItemPartsToOrderItemPartResponseModel"
)

@_attrs_define
class QualerApiModelsServiceOrderItemPartsToOrderItemPartResponseModel:
    service_order_item_part_id: Unset | int = ...
    service_order_item_id: Unset | int = ...
    name: Unset | str = ...
    description: Unset | str = ...
    discount: Unset | float = ...
    is_taxable: Unset | bool = ...
    is_hourly_pricing: Unset | bool = ...
    price: Unset | float = ...
    unit_name: Unset | str = ...
    quantity: Unset | float = ...
    delivery_charge: Unset | float = ...
    time_spent_in_minutes: Unset | float = ...
    free_quantity: Unset | int = ...
    service_order_charge_type: (
        Unset
        | QualerApiModelsServiceOrderItemPartsToOrderItemPartResponseModelServiceOrderChargeType
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
