import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_service_orders_from_order_item_update_model_as_found_check import (
    QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsFoundCheck as QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsFoundCheck,
)
from ..models.qualer_api_models_service_orders_from_order_item_update_model_as_found_result import (
    QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsFoundResult as QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsFoundResult,
)
from ..models.qualer_api_models_service_orders_from_order_item_update_model_as_left_check import (
    QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsLeftCheck as QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsLeftCheck,
)
from ..models.qualer_api_models_service_orders_from_order_item_update_model_as_left_result import (
    QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsLeftResult as QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsLeftResult,
)
from ..models.qualer_api_models_service_orders_from_order_item_update_model_result_status import (
    QualerApiModelsServiceOrdersFromOrderItemUpdateModelResultStatus as QualerApiModelsServiceOrdersFromOrderItemUpdateModelResultStatus,
)
from ..models.qualer_api_models_service_orders_from_order_item_update_model_work_status import (
    QualerApiModelsServiceOrdersFromOrderItemUpdateModelWorkStatus as QualerApiModelsServiceOrdersFromOrderItemUpdateModelWorkStatus,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsServiceOrdersFromOrderItemUpdateModel")

@_attrs_define
class QualerApiModelsServiceOrdersFromOrderItemUpdateModel:
    service_comments: Unset | str = ...
    private_comments: Unset | str = ...
    service_notes: Unset | str = ...
    service_total: Unset | float = ...
    repairs_total: Unset | float = ...
    parts_total: Unset | float = ...
    work_status: (
        Unset | QualerApiModelsServiceOrdersFromOrderItemUpdateModelWorkStatus
    ) = ...
    custom_work_status: Unset | str = ...
    is_limited: Unset | bool = ...
    checked_on: Unset | datetime.datetime = ...
    checked_by_name: Unset | str = ...
    completed_on: Unset | datetime.datetime = ...
    completed_by_name: Unset | str = ...
    as_found_check: (
        Unset | QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsFoundCheck
    ) = ...
    as_left_check: (
        Unset | QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsLeftCheck
    ) = ...
    result_status: (
        Unset | QualerApiModelsServiceOrdersFromOrderItemUpdateModelResultStatus
    ) = ...
    as_found_result: (
        Unset | QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsFoundResult
    ) = ...
    as_left_result: (
        Unset | QualerApiModelsServiceOrdersFromOrderItemUpdateModelAsLeftResult
    ) = ...
    equipment_id: Unset | str = ...
    legacy_id: Unset | str = ...
    serial_number: Unset | str = ...
    serial_number_change: Unset | str = ...
    asset_tag: Unset | str = ...
    asset_tag_change: Unset | str = ...
    asset_user: Unset | str = ...
    asset_user_change: Unset | str = ...
    provider_technician: Unset | str = ...
    provider_phone: Unset | str = ...
    provider_company: Unset | str = ...
    certificate_number: Unset | str = ...
    service_date: Unset | datetime.datetime = ...
    next_service_date: Unset | datetime.datetime = ...
    vendor_tag: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
