from pydantic import BaseModel, StrictFloat as StrictFloat, StrictInt as StrictInt, StrictStr as StrictStr

class QualerApiModelsEnvironmentFromEnvironmentModel(BaseModel):
    station_id: StrictInt | None
    factor_id: StrictStr | None
    factor_name: StrictStr | None
    factor_value: StrictFloat | StrictInt | None
    unit_of_measure: StrictStr | None
    def factor_id_validate_enum(cls, value): ...
    class Config:
        allow_population_by_field_name: bool
        validate_assignment: bool
    def to_str(self) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json_str: str) -> QualerApiModelsEnvironmentFromEnvironmentModel: ...
    def to_dict(self): ...
    @classmethod
    def from_dict(cls, obj: dict) -> QualerApiModelsEnvironmentFromEnvironmentModel: ...
