import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_address_to_address_response_model import (
    QualerApiModelsAddressToAddressResponseModel as QualerApiModelsAddressToAddressResponseModel,
)
from ..models.qualer_api_models_attributes_to_attribute_response import (
    QualerApiModelsAttributesToAttributeResponse as QualerApiModelsAttributesToAttributeResponse,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsClientsToClientCompanyResponseModel")

@_attrs_define
class QualerApiModelsClientsToClientCompanyResponseModel:
    company_id: Unset | int = ...
    account_number_text: Unset | str = ...
    account_number: Unset | int = ...
    currency_id: Unset | int = ...
    client_status: Unset | str = ...
    company_name: Unset | str = ...
    company_description: Unset | str = ...
    domain_name: Unset | str = ...
    custom_client_name: Unset | str = ...
    legacy_id: Unset | str = ...
    updated_on_utc: Unset | datetime.datetime = ...
    account_representative_employee_id: Unset | int = ...
    account_representative_site_id: Unset | int = ...
    account_manager_employee_id: Unset | int = ...
    billing_address: Unset | QualerApiModelsAddressToAddressResponseModel = ...
    shipping_address: Unset | QualerApiModelsAddressToAddressResponseModel = ...
    attributes: Unset | list["QualerApiModelsAttributesToAttributeResponse"] = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
