from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_maintenance_plans_to_maintenance_task_response import (
    QualerApiModelsMaintenancePlansToMaintenanceTaskResponse as QualerApiModelsMaintenancePlansToMaintenanceTaskResponse,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsMaintenancePlansToMaintenancePlanResponse")

@_attrs_define
class QualerApiModelsMaintenancePlansToMaintenancePlanResponse:
    maintenance_plan_id: Unset | int = ...
    maintenance_plan_name: Unset | str = ...
    is_template: Unset | bool = ...
    company_name: Unset | str = ...
    maintenance_tasks: (
        Unset | list["QualerApiModelsMaintenancePlansToMaintenanceTaskResponse"]
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
