from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsAddressAddressModel")

@_attrs_define
class QualerApiModelsAddressAddressModel:
    first_name: Unset | str = ...
    last_name: Unset | str = ...
    email: Unset | str = ...
    company: Unset | str = ...
    city: Unset | str = ...
    address_1: Unset | str = ...
    address_2: Unset | str = ...
    zip_postal_code: Unset | str = ...
    phone_number: Unset | str = ...
    fax_number: Unset | str = ...
    attention_1: Unset | str = ...
    attention_2: Unset | str = ...
    country: Unset | str = ...
    state_province: Unset | str = ...
    state_province_abbreviation: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
