import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsAssetReservationFromUpsertAssetReservationModel")

@_attrs_define
class QualerApiModelsAssetReservationFromUpsertAssetReservationModel:
    asset_id: Unset | int = ...
    product_id: Unset | int = ...
    reservation_id: Unset | int = ...
    service_order_id: Unset | int = ...
    begin_date: Unset | datetime.datetime = ...
    end_date: Unset | datetime.datetime = ...
    reserved_by: Unset | int = ...
    reserved_by_name: Unset | str = ...
    comments: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
