import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_as_found_result import (
    QualerApiModelsAssetToClientAssetManagerResponseModelAsFoundResult as QualerApiModelsAssetToClientAssetManagerResponseModelAsFoundResult,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_as_left_result import (
    QualerApiModelsAssetToClientAssetManagerResponseModelAsLeftResult as QualerApiModelsAssetToClientAssetManagerResponseModelAsLeftResult,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_due_status import (
    QualerApiModelsAssetToClientAssetManagerResponseModelDueStatus as QualerApiModelsAssetToClientAssetManagerResponseModelDueStatus,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_record_type import (
    QualerApiModelsAssetToClientAssetManagerResponseModelRecordType as QualerApiModelsAssetToClientAssetManagerResponseModelRecordType,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_result_status import (
    QualerApiModelsAssetToClientAssetManagerResponseModelResultStatus as QualerApiModelsAssetToClientAssetManagerResponseModelResultStatus,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_service_order_status import (
    QualerApiModelsAssetToClientAssetManagerResponseModelServiceOrderStatus as QualerApiModelsAssetToClientAssetManagerResponseModelServiceOrderStatus,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_tool_role import (
    QualerApiModelsAssetToClientAssetManagerResponseModelToolRole as QualerApiModelsAssetToClientAssetManagerResponseModelToolRole,
)
from ..models.qualer_api_models_asset_to_client_asset_manager_response_model_work_status import (
    QualerApiModelsAssetToClientAssetManagerResponseModelWorkStatus as QualerApiModelsAssetToClientAssetManagerResponseModelWorkStatus,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar("T", bound="QualerApiModelsAssetToClientAssetManagerResponseModel")

@_attrs_define
class QualerApiModelsAssetToClientAssetManagerResponseModel:
    asset_id: Unset | int = ...
    asset_name: Unset | str = ...
    asset_description: Unset | str = ...
    asset_maker: Unset | str = ...
    record_type: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelRecordType
    ) = ...
    parent_asset_id: Unset | int = ...
    children_count: Unset | int = ...
    site_id: Unset | int = ...
    serial_number: Unset | str = ...
    asset_tag: Unset | str = ...
    asset_user: Unset | str = ...
    equipment_id: Unset | str = ...
    legacy_identifier: Unset | str = ...
    criticality: Unset | str = ...
    condition: Unset | str = ...
    asset_class: Unset | str = ...
    activation_date: Unset | datetime.datetime = ...
    retirment_date: Unset | datetime.datetime = ...
    client_vendor_id: Unset | int = ...
    company_name: Unset | str = ...
    site_name: Unset | str = ...
    asset_has_image: Unset | bool = ...
    has_image: Unset | bool = ...
    parent_has_image: Unset | bool = ...
    pool_id: Unset | int = ...
    pool: Unset | str = ...
    product_id: Unset | int = ...
    parent_product_id: Unset | int = ...
    product_name: Unset | str = ...
    parent_product_name: Unset | str = ...
    category_id: Unset | int = ...
    root_category_id: Unset | int = ...
    category_name: Unset | str = ...
    root_category_name: Unset | str = ...
    manufacturer_id: Unset | int = ...
    manufacturer: Unset | str = ...
    display_part_number: Unset | str = ...
    display_name: Unset | str = ...
    manufacturer_part_number: Unset | str = ...
    asset_room: Unset | str = ...
    location: Unset | str = ...
    station: Unset | str = ...
    tool_role: Unset | QualerApiModelsAssetToClientAssetManagerResponseModelToolRole = (
        ...
    )
    tool_id: Unset | int = ...
    department_id: Unset | int = ...
    department_name: Unset | str = ...
    custodian_name: Unset | str = ...
    warranty: Unset | str = ...
    warranty_end: Unset | datetime.datetime = ...
    is_warranty_expired: Unset | bool = ...
    depreciation_method: Unset | int = ...
    depreciation_basis: Unset | float = ...
    salvage_value: Unset | float = ...
    total_service_cost: Unset | float = ...
    life_span_months: Unset | int = ...
    due_for_replacement_date: Unset | datetime.datetime = ...
    depreciation_proc: Unset | float = ...
    purchase_date: Unset | datetime.datetime = ...
    purchase_cost: Unset | float = ...
    time_in_service: Unset | int = ...
    retirement_reason: Unset | str = ...
    residual_cost: Unset | float = ...
    employee_id: Unset | int = ...
    asset_collection_id: Unset | int = ...
    asset_service_record_id: Unset | int = ...
    result_status: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelResultStatus
    ) = ...
    as_found_result: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelAsFoundResult
    ) = ...
    as_left_result: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelAsLeftResult
    ) = ...
    last_service_date: Unset | datetime.datetime = ...
    last_service: Unset | str = ...
    next_service_date: Unset | datetime.datetime = ...
    next_service: Unset | str = ...
    service_schedule_segment_id: Unset | int = ...
    service_schedule_id: Unset | int = ...
    service_schedule: Unset | str = ...
    in_service: Unset | bool = ...
    in_last_service: Unset | bool = ...
    service_order_id: Unset | int = ...
    service_order_status: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelServiceOrderStatus
    ) = ...
    custom_order_number: Unset | str = ...
    service_order_item_id: Unset | int = ...
    vendor: Unset | str = ...
    technician: Unset | str = ...
    certificate_number: Unset | str = ...
    due_trigger_date: Unset | datetime.datetime = ...
    past_due_trigger_date: Unset | datetime.datetime = ...
    due_status: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelDueStatus
    ) = ...
    work_status: (
        Unset | QualerApiModelsAssetToClientAssetManagerResponseModelWorkStatus
    ) = ...
    service_tag: Unset | str = ...
    service_site_name: Unset | str = ...
    service_site_id: Unset | int = ...
    standard_title: Unset | str = ...
    schedules: Unset | str = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
