from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.qualer_api_models_measurements_to_update_measurement_condition_factor_response import (
    QualerApiModelsMeasurementsToUpdateMeasurementConditionFactorResponse as QualerApiModelsMeasurementsToUpdateMeasurementConditionFactorResponse,
)
from ..models.qualer_api_models_measurements_to_update_measurement_response_model import (
    QualerApiModelsMeasurementsToUpdateMeasurementResponseModel as QualerApiModelsMeasurementsToUpdateMeasurementResponseModel,
)
from ..models.qualer_api_models_measurements_to_update_measurement_tool_response_model import (
    QualerApiModelsMeasurementsToUpdateMeasurementToolResponseModel as QualerApiModelsMeasurementsToUpdateMeasurementToolResponseModel,
)
from ..types import UNSET as UNSET
from ..types import Unset as Unset

T = TypeVar(
    "T", bound="QualerApiModelsMeasurementsToUpdateMeasurementPointResponseModel"
)

@_attrs_define
class QualerApiModelsMeasurementsToUpdateMeasurementPointResponseModel:
    measurement_point_id: Unset | int = ...
    specification_name: Unset | str = ...
    unit_of_measure: Unset | str = ...
    expected_value: Unset | float = ...
    base_value: Unset | float = ...
    test_value: Unset | float = ...
    nominal: Unset | float = ...
    range_min: Unset | float = ...
    range_max: Unset | float = ...
    tolerance_type: Unset | str = ...
    tolerance_mode: Unset | str = ...
    tolerance_unit: Unset | str = ...
    precision_type: Unset | str = ...
    precision: Unset | float = ...
    tolerance_minimum: Unset | float = ...
    tolerance_maximum: Unset | float = ...
    resolution: Unset | float = ...
    resolution_count: Unset | float = ...
    is_accredited: Unset | bool = ...
    linked_measurement_point_id: Unset | int = ...
    hysteresis_point: Unset | str = ...
    hide_from_certificate: Unset | bool = ...
    is_measurement_not_taken: Unset | bool = ...
    measurement_not_taken_result: Unset | str = ...
    measurement_not_taken_reason: Unset | str = ...
    influence_parameter_1_parameter_id: Unset | int = ...
    influence_parameter_1_value: Unset | str = ...
    influence_parameter_2_parameter_id: Unset | int = ...
    influence_parameter_2_value: Unset | str = ...
    measurements: (
        Unset | list["QualerApiModelsMeasurementsToUpdateMeasurementResponseModel"]
    ) = ...
    measurement_condition_factors: (
        Unset
        | list["QualerApiModelsMeasurementsToUpdateMeasurementConditionFactorResponse"]
    ) = ...
    primary_measurement_tool: (
        Unset | QualerApiModelsMeasurementsToUpdateMeasurementToolResponseModel
    ) = ...
    secondary_measurement_tool: (
        Unset | QualerApiModelsMeasurementsToUpdateMeasurementToolResponseModel
    ) = ...
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> T: ...
    @property
    def additional_keys(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
