from office365.entity import Entity as Entity
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)

class WorkbookPivotTable(Entity):
    def refresh(self): ...
    def refresh_all(self): ...
    @property
    def name(self) -> str | None: ...
    @property
    def worksheet(self): ...
