from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.entity import Entity as Entity

class InformationRightsManagementFileSettings(Entity):
    def reset(self): ...
    @property
    def allow_print(self) -> bool | None: ...
    @allow_print.setter
    def allow_print(self, value: bool) -> None: ...
    @property
    def allow_script(self) -> bool | None: ...
    @allow_script.setter
    def allow_script(self, value: bool) -> None: ...
    @property
    def allow_write_copy(self) -> bool | None: ...
