from _typeshed import Incomplete
from office365.directory.audit.provisioning.service_principal import ProvisioningServicePrincipal as ProvisioningServicePrincipal
from office365.entity import Entity as Entity

class ProvisioningObjectSummary(Entity):
    @property
    def activity_datetime(self): ...
    @property
    def change_id(self) -> str | None: ...
    @property
    def cycle_id(self) -> str | None: ...
    @property
    def duration_in_milliseconds(self) -> int | None: ...
    @property
    def service_principal(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
