from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.entity_collection import EntityCollection as EntityCollection
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class UserActivity(Entity):
    @property
    def activation_url(self) -> str | None: ...
    @property
    def activity_source_host(self) -> str | None: ...
    @property
    def app_activity_id(self) -> str | None: ...
    @property
    def app_display_name(self) -> str | None: ...
    @property
    def created_datetime(self): ...
    @property
    def expiration_datetime(self): ...
    @property
    def history_items(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
