from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.listitems.versions.collection import (
    ListItemVersionCollection as ListItemVersionCollection,
)

class ListItemVersion(Entity):
    @property
    def version_id(self) -> int | None: ...
    @property
    def version_label(self) -> str | None: ...
    @property
    def is_current_version(self) -> bool | None: ...
    @property
    def created(self): ...
    @property
    def created_by(self): ...
    @property
    def fields(self): ...
    @property
    def file_version(self): ...
    @property
    def property_ref_name(self): ...
    @property
    def parent_collection(self) -> ListItemVersionCollection: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
