from office365.sharepoint.directory.helper import SPHelper as SPHelper
from office365.sharepoint.directory.members_info import MembersInfo as MembersInfo
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.entity_collection import EntityCollection as EntityCollection

class Group(Entity):
    def get_members_info(self, row_limit): ...
    def get_members(self): ...
    def get_owners(self): ...
    @property
    def entity_type_name(self): ...
