[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  migrations
  | htmlcov
  | \.git
  | \.pytest_cache
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["app", "routes", "utils", "db", "tests"]
skip_glob = ["migrations/*", "htmlcov/*", ".git/*"]

[tool.coverage.run]
omit = [
    "tests/*",
    "*/test_*.py",
]
