from _typeshed import Incomplete
from office365.entity_collection import EntityCollection as EntityCollection
from office365.onedrive.lists.list import List as List
from office365.runtime.paths.v4.entity import EntityPath as EntityPath
from office365.runtime.queries.create_entity import CreateEntityQuery as CreateEntityQuery

class ListCollection(EntityCollection[List]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def add(self, display_name, list_template: str = 'genericList'): ...
    def get_by_name(self, name): ...
    def get_by_id(self, list_id): ...
