from office365.sharepoint.fields.field import Field as Field

class FieldDateTime(Field):
    @property
    def datetime_calendar_type(self) -> int | None: ...
    @datetime_calendar_type.setter
    def datetime_calendar_type(self, value: int) -> None: ...
    @property
    def date_format(self) -> str | None: ...
    @property
    def display_format(self) -> int | None: ...
    @property
    def friendly_display_format(self) -> int | None: ...
    @property
    def time_format(self) -> str | None: ...
