from office365.sharepoint.fields.field import Field as Field

class FieldMultiLineText(Field):
    def __init__(self, context) -> None: ...
    @property
    def allow_hyperlink(self) -> bool | None: ...
    @allow_hyperlink.setter
    def allow_hyperlink(self, val: bool) -> None: ...
    @property
    def number_of_lines(self) -> int | None: ...
    @number_of_lines.setter
    def number_of_lines(self, val: int) -> None: ...
    @property
    def restricted_mode(self) -> bool | None: ...
    @property
    def rich_text(self) -> bool | None: ...
    @property
    def unlimited_length_in_document_library(self) -> bool | None: ...
    @property
    def wiki_linking(self) -> bool | None: ...
