from office365.sharepoint.fields.field import Field as Field

class FieldNumber(Field):
    @property
    def display_format(self) -> int | None: ...
    @property
    def comma_separator(self) -> str | None: ...
    @comma_separator.setter
    def comma_separator(self, value: str) -> None: ...
    @property
    def show_as_percentage(self) -> bool | None: ...
    @show_as_percentage.setter
    def show_as_percentage(self, value: bool) -> None: ...
