from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity

class RelatedField(Entity):
    @property
    def field_id(self) -> str | None: ...
    @property
    def list_id(self) -> str | None: ...
    @property
    def web_id(self) -> str | None: ...
    @property
    def relationship_delete_behavior(self) -> int | None: ...
    @property
    def lookup_list(self): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
