from office365.entity import Entity as Entity
from office365.runtime.types.collections import StringCollection as StringCollection

class PermissionGrantConditionSet(Entity):
    @property
    def client_application_ids(self): ...
    @property
    def client_application_publisher_ids(self): ...
    @property
    def client_applications_from_verified_publisher_only(self) -> bool | None: ...
    @property
    def permissions(self): ...
    @property
    def resource_application(self) -> str | None: ...
