from office365.directory.permissions.default_user_role import DefaultUserRolePermissions as DefaultUserRolePermissions
from office365.directory.policies.base import PolicyBase as PolicyBase

class AuthorizationPolicy(PolicyBase):
    @property
    def allowed_to_sign_up_email_based_subscriptions(self) -> bool | None: ...
    @property
    def allowed_to_use_sspr(self) -> bool | None: ...
    @property
    def allow_email_verified_users_to_join_organization(self) -> bool | None: ...
    @property
    def allow_invites_from(self) -> str | None: ...
    @property
    def allow_user_consent_for_risky_apps(self) -> bool | None: ...
    @property
    def block_msol_powershell(self) -> bool | None: ...
    @property
    def default_user_role_permissions(self) -> DefaultUserRolePermissions | None: ...
