import datetime
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity

class PushNotificationSubscriber(Entity):
    @property
    def custom_args(self) -> str | None: ...
    @property
    def service_token(self) -> str | None: ...
    @service_token.setter
    def service_token(self, value: str) -> None: ...
    @property
    def device_app_instance_id(self) -> str | None: ...
    @property
    def last_modified_time_stamp(self) -> datetime.datetime | None: ...
    @property
    def registration_time_stamp(self) -> datetime.datetime | None: ...
    @property
    def user(self): ...
