from _typeshed import Incomplete
from datetime import datetime
from office365.onedrive.listitems.list_item import ListItem as ListItem
from office365.runtime.client_value_collection import ClientValueCollection as ClientValueCollection
from office365.runtime.paths.service_operation import ServiceOperationPath as ServiceOperationPath
from office365.runtime.paths.v3.entity import EntityPath as EntityPath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.runtime.types.collections import StringCollection as StringCollection
from office365.sharepoint.client_context import ClientContext as ClientContext
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.internal.paths.static_operation import StaticOperationPath as StaticOperationPath
from office365.sharepoint.tenant.administration.deny_add_and_customize_pages_status import DenyAddAndCustomizePagesStatus as DenyAddAndCustomizePagesStatus
from office365.sharepoint.tenant.administration.spo_operation import SpoOperation as SpoOperation
from office365.sharepoint.translation.resource_entry import SPResourceEntry as SPResourceEntry

class SiteProperties(Entity):
    @staticmethod
    def clear_sharing_lock_down(context: ClientContext, site_url: str) -> SiteProperties: ...
    def update(self): ...
    def update_ex(self): ...
    @property
    def allow_downloading_non_web_viewable_files(self) -> bool | None: ...
    @property
    def allow_editing(self) -> bool | None: ...
    @property
    def allow_self_service_upgrade(self) -> bool | None: ...
    @property
    def anonymous_link_expiration_in_days(self) -> int | None: ...
    @property
    def apply_to_existing_document_libraries(self) -> bool | None: ...
    @property
    def apply_to_new_document_libraries(self) -> bool | None: ...
    @property
    def archived_by(self) -> str | None: ...
    @property
    def archived_time(self) -> datetime | None: ...
    @property
    def block_download_links_file_type(self) -> int | None: ...
    @property
    def block_download_microsoft365_group_ids(self) -> StringCollection | None: ...
    @property
    def block_download_policy_file_type_ids(self) -> StringCollection | None: ...
    @property
    def created_time(self) -> datetime | None: ...
    @property
    def deny_add_and_customize_pages(self) -> int | None: ...
    @deny_add_and_customize_pages.setter
    def deny_add_and_customize_pages(self, value: int) -> None: ...
    @property
    def last_content_modified_date(self) -> datetime | None: ...
    @property
    def group_owner_login_name(self) -> str | None: ...
    @property
    def is_hub_site(self) -> bool | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def title_translations(self) -> str | None: ...
    @property
    def owner_login_name(self) -> str | None: ...
    @property
    def webs_count(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def compatibility_level(self) -> str | None: ...
    @property
    def lock_state(self) -> str | None: ...
    @property
    def sharing_capability(self) -> int | None: ...
    @sharing_capability.setter
    def sharing_capability(self, value: int) -> None: ...
    @property
    def time_zone_id(self) -> str | None: ...
    @property
    def entity_type_name(self) -> str: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
