from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.runtime.types.collections import StringCollection as StringCollection

class AttachmentSession(Entity):
    @property
    def content(self): ...
    @property
    def expiration_datetime(self): ...
    @property
    def next_expected_ranges(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
