from _typeshed import Incomplete
from office365.runtime.paths.service_operation import ServiceOperationPath as ServiceOperationPath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.entity_collection import EntityCollection as EntityCollection
from office365.sharepoint.files.versions.version import FileVersion as FileVersion

class FileVersionCollection(EntityCollection[FileVersion]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def get_by_id(self, version_id): ...
    def get_by_label(self, label): ...
    def delete_all(self): ...
    def delete_by_id(self, vid): ...
    def delete_by_label(self, label): ...
    def recycle_by_id(self, vid): ...
    def recycle_by_label(self, label): ...
    def restore_by_label(self, label): ...
