from _typeshed import Incomplete
from datetime import datetime
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.paths.v3.entity import EntityPath as EntityPath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.entity import Entity as Entity
from typing import AnyStr, IO
from typing_extensions import Self

class FileVersion(Entity):
    def download(self, file_object: IO) -> Self: ...
    def open_binary_stream(self) -> ClientResult[AnyStr]: ...
    def open_binary_stream_with_options(self, open_options: int) -> ClientResult[AnyStr]: ...
    @property
    def created(self) -> datetime | None: ...
    @property
    def created_by(self): ...
    @property
    def id(self) -> int | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def version_label(self) -> str | None: ...
    @property
    def is_current_version(self) -> bool | None: ...
    @property
    def checkin_comment(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, key, value, persist_changes: bool = True): ...
