from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.runtime.types.collections import StringCollection as StringCollection

class OutlookItem(Entity):
    @property
    def change_key(self) -> str | None: ...
    @property
    def categories(self): ...
    @property
    def created_datetime(self): ...
    @property
    def last_modified_datetime(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
