from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.navigation.node_collection import (
    NavigationNodeCollection as NavigationNodeCollection,
)

class Navigation(Entity):
    @property
    def use_shared(self): ...
    @use_shared.setter
    def use_shared(self, value) -> None: ...
    @property
    def quick_launch(self): ...
    @property
    def top_navigation_bar(self): ...
    def set_property(self, name, value, persist_changes: bool = True) -> None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
