from office365.entity import Entity as Entity
from office365.onedrive.driveitems.thumbnail import Thumbnail as Thumbnail

class ThumbnailSet(Entity):
    @property
    def large(self): ...
    @property
    def medium(self): ...
    @property
    def small(self): ...
    @property
    def source(self): ...
