from ... import errors as errors
from ...client import AuthenticatedClient as AuthenticatedClient
from ...client import Client as Client
from ...models.qualer_api_models_clients_to_employee_response_model import (
    QualerApiModelsClientsToEmployeeResponseModel as QualerApiModelsClientsToEmployeeResponseModel,
)
from ...types import UNSET as UNSET
from ...types import Response as Response
from ...types import Unset as Unset

def sync_detailed(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> Response[list["QualerApiModelsClientsToEmployeeResponseModel"]]: ...
def sync(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> list["QualerApiModelsClientsToEmployeeResponseModel"] | None: ...
async def asyncio_detailed(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> Response[list["QualerApiModelsClientsToEmployeeResponseModel"]]: ...
async def asyncio(
    *, client: AuthenticatedClient | Client, model_search_string: Unset | str = ...
) -> list["QualerApiModelsClientsToEmployeeResponseModel"] | None: ...
