from office365.runtime.odata.type import ODataType as ODataType
from office365.runtime.paths.service_operation import ServiceOperationPath as ServiceOperationPath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.principal.type import PrincipalType as PrincipalType

class Principal(Entity):
    @property
    def id(self) -> int | None: ...
    @property
    def title(self) -> str | None: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def login_name(self) -> str | None: ...
    @property
    def user_principal_name(self) -> str | None: ...
    @property
    def is_hidden_in_ui(self) -> bool | None: ...
    @property
    def principal_type(self) -> int | None: ...
    @property
    def principal_type_name(self): ...
    @property
    def property_ref_name(self): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
