from office365.entity import Entity as Entity
from office365.onedrive.workbooks.ranges.range import WorkbookRange as WorkbookRange
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.function import FunctionQuery as FunctionQuery

class WorkbookNamedItem(Entity):
    def range(self): ...
    @property
    def name(self) -> str | None: ...
    @property
    def comment(self) -> str | None: ...
    @property
    def scope(self) -> str | None: ...
    @property
    def worksheet(self): ...
    @property
    def property_ref_name(self) -> str: ...
