from _typeshed import Incomplete
from office365.entity_collection import EntityCollection as EntityCollection
from office365.onedrive.workbooks.tables.rows.row import (
    WorkbookTableRow as WorkbookTableRow,
)
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.queries.function import FunctionQuery as FunctionQuery

class WorkbookTableRowCollection(EntityCollection[WorkbookTableRow]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def add(self, values, index: Incomplete | None = None): ...
    def count(self): ...
    def item_at(self, index: int) -> WorkbookTableRow: ...
