from typing import Iterator

from _typeshed import Incomplete
from office365.runtime.client_value import ClientValue as ClientValue
from office365.sharepoint.permissions.kind import PermissionKind as PermissionKind

class BasePermissions(ClientValue):
    High: int
    Low: int
    def __init__(self) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def set(self, perm) -> None: ...
    def has(self, perm: int) -> bool: ...
    def clear_all(self) -> None: ...
    def to_json(self, json_format: Incomplete | None = None): ...
    @property
    def permission_levels(self): ...
