from office365.runtime.client_runtime_context import ClientRuntimeContext as ClientRuntimeContext
from office365.runtime.queries.client_query import ClientQuery as ClientQuery
from office365.runtime.queries.read_entity import ReadEntityQuery as ReadEntityQuery

def create_boundary(prefix, compact: bool = False): ...

class BatchQuery(ClientQuery):
    def __init__(self, context: ClientRuntimeContext, queries: list[ClientQuery] = None) -> None: ...
    def add(self, query: ClientQuery) -> None: ...
    @property
    def ordered_queries(self): ...
    @property
    def current_boundary(self): ...
    @property
    def change_sets(self): ...
    @property
    def queries(self) -> list[ClientQuery]: ...
    @property
    def get_queries(self): ...
    @property
    def has_change_sets(self): ...
    @property
    def url(self): ...
    @property
    def return_type(self): ...
