from _typeshed import Incomplete
from office365.directory.audit.activity_initiator import (
    AuditActivityInitiator as AuditActivityInitiator,
)
from office365.directory.audit.target_resource import TargetResource as TargetResource
from office365.entity import Entity as Entity
from office365.runtime.client_value_collection import (
    ClientValueCollection as ClientValueCollection,
)

class DirectoryAudit(Entity):
    @property
    def activity_datetime(self): ...
    @property
    def activity_display_name(self) -> str | None: ...
    @property
    def additional_details(self) -> dict | None: ...
    @property
    def category(self) -> str | None: ...
    @property
    def correlation_id(self) -> str | None: ...
    @property
    def initiated_by(self): ...
    @property
    def operation_type(self) -> str | None: ...
    @property
    def logged_by_service(self) -> str | None: ...
    @property
    def result(self) -> str | None: ...
    @property
    def result_reason(self) -> str | None: ...
    @property
    def target_resources(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
