from _typeshed import Incomplete
from office365.directory.permissions.identity_set import IdentitySet as IdentitySet
from office365.entity import Entity as Entity
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.teams.bots.teamwork_bot import TeamworkBot as TeamworkBot

class TeamsAppDefinition(Entity):
    @property
    def bot(self): ...
    @property
    def created_by(self): ...
    @property
    def description(self): ...
    @property
    def last_modified_datetime(self): ...
    @property
    def teams_app_id(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
