from _typeshed import Incomplete
from office365.sharepoint.fields.lookup import FieldLookup as FieldLookup
from office365.sharepoint.taxonomy.create_xml_parameters import (
    TaxonomyFieldCreateXmlParameters as TaxonomyFieldCreateXmlParameters,
)

class TaxonomyField(FieldLookup):
    def set_field_value_by_value(self, item, tax_value): ...
    @staticmethod
    def create(
        fields,
        name,
        term_set_id,
        term_store_id: Incomplete | None = None,
        allow_multiple_values: bool = False,
        return_type: Incomplete | None = None,
    ): ...
    @property
    def anchor_id(self) -> str | None: ...
    @property
    def create_values_in_edit_form(self) -> bool | None: ...
    @property
    def is_anchor_valid(self) -> bool | None: ...
    @property
    def is_doc_tags_enabled(self) -> bool | None: ...
    @property
    def is_keyword(self) -> bool | None: ...
    @property
    def is_path_rendered(self) -> bool | None: ...
    @property
    def is_term_set_valid(self) -> bool | None: ...
    @property
    def open(self) -> bool | None: ...
    @property
    def ssp_id(self) -> str | None: ...
    @property
    def target_template(self) -> str | None: ...
    @property
    def term_set_id(self) -> str | None: ...
    @property
    def text_field_id(self) -> str | None: ...
    @property
    def text_field(self): ...
    @property
    def user_created(self) -> bool | None: ...
    @property
    def entity_type_name(self): ...
