from office365.entity import Entity as Entity

class WorkbookRangeFont(Entity):
    @property
    def bold(self) -> bool | None: ...
    @property
    def color(self) -> str | None: ...
    @property
    def italic(self) -> bool | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def size(self) -> float | None: ...
    @property
    def underline(self) -> bool | None: ...
