from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.onedrive.workbooks.ranges.format import WorkbookRangeFormat as WorkbookRangeFormat
from office365.onedrive.workbooks.ranges.sort import WorkbookRangeSort as WorkbookRangeSort
from office365.onedrive.workbooks.ranges.view import WorkbookRangeView as WorkbookRangeView
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.function import FunctionQuery as FunctionQuery
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery

class WorkbookRange(Entity):
    def cell(self, row, column): ...
    def clear(self, apply_to: Incomplete | None = None): ...
    def insert(self, shift): ...
    def last_row(self): ...
    def visible_view(self): ...
    def used_range(self, values_only: bool = False): ...
    @property
    def address(self) -> str | None: ...
    @property
    def address_local(self) -> str | None: ...
    @property
    def cell_count(self) -> int | None: ...
    @property
    def column_count(self) -> int | None: ...
    @property
    def column_hidden(self) -> bool | None: ...
    @property
    def column_index(self) -> int | None: ...
    @property
    def row_index(self) -> int | None: ...
    @property
    def format(self): ...
    @property
    def sort(self): ...
    @property
    def values(self) -> list: ...
    @property
    def value_types(self) -> list: ...
    @property
    def worksheet(self): ...
