from office365.sharepoint.entity import Entity as Entity

class EmbedDataV1(Entity):
    def url(self) -> str | None: ...
    def video_id(self) -> str | None: ...
    def web_id(self) -> str | None: ...
