from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.client_context import ClientContext as ClientContext
from office365.sharepoint.entity import Entity as Entity

class TenantAdminEndpoints(Entity):
    def __init__(self, context: ClientContext) -> None: ...
    @property
    def aad_admin_center_endpoint(self) -> str | None: ...
    @property
    def cdn_default_endpoint(self) -> str | None: ...
    @property
    def o365_admin_center_endpoint(self) -> str | None: ...
    @property
    def cfrms_graph_endpoint(self) -> str | None: ...
    @property
    def migration_agent_url(self) -> str | None: ...
    @property
    def mini_maven_endpoint(self) -> str | None: ...
    @property
    def sp_migration_tool_url(self) -> str | None: ...
    @property
    def entity_type_name(self): ...
