class AuthCookies:
    def __init__(self, cookies: dict) -> None: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def cookie_header(self): ...
    @property
    def fed_auth(self) -> str | None: ...
    @property
    def spo_idcrl(self) -> str | None: ...
    @property
    def rt_fa(self) -> str | None: ...
    def to_json(self): ...
    @classmethod
    def from_json(cls, json_data): ...
