from _typeshed import Incomplete
from office365.runtime.paths.service_operation import (
    ServiceOperationPath as ServiceOperationPath,
)
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.runtime.types.collections import StringCollection as StringCollection
from office365.sharepoint.entity_collection import EntityCollection as EntityCollection
from office365.sharepoint.recyclebin.item import RecycleBinItem as RecycleBinItem

class RecycleBinItemCollection(EntityCollection[RecycleBinItem]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def delete_all_second_stage_items(self): ...
    def delete_by_ids(self, ids): ...
    def move_to_second_stage_by_ids(self, ids): ...
    def move_all_to_second_stage(self): ...
    def get_by_id(self, recycle_bin_id): ...
    def delete_all(self): ...
    def restore_all(self): ...
