from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.entity_collection import EntityCollection as EntityCollection
from office365.onedrive.analytics.item_action_stat import (
    ItemActionStat as ItemActionStat,
)
from office365.onedrive.analytics.item_activity import ItemActivity as ItemActivity
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class ItemActivityStat(Entity):
    @property
    def access(self): ...
    @property
    def create(self): ...
    @property
    def delete(self): ...
    @property
    def edit(self): ...
    @property
    def end_datetime(self): ...
    @property
    def is_trending(self) -> bool | None: ...
    @property
    def move(self): ...
    @property
    def start_datetime(self): ...
    @property
    def activities(self) -> EntityCollection[ItemActivity]: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
