from _typeshed import Incomplete
from office365.directory.rolemanagement.app_scope import AppScope as AppScope
from office365.directory.rolemanagement.unifiedrole.definition import (
    UnifiedRoleDefinition as UnifiedRoleDefinition,
)
from office365.entity import Entity as Entity
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class UnifiedRoleAssignment(Entity):
    @property
    def app_scope_id(self) -> str | None: ...
    @property
    def condition(self) -> str | None: ...
    @property
    def principal_id(self) -> str | None: ...
    @property
    def role_definition_id(self) -> str | None: ...
    @property
    def directory_scope_id(self) -> str | None: ...
    @property
    def role_definition(self): ...
    @property
    def app_scope(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
