from _typeshed import Incomplete
from office365.runtime.paths.service_operation import (
    ServiceOperationPath as ServiceOperationPath,
)
from office365.runtime.queries.create_entity import (
    CreateEntityQuery as CreateEntityQuery,
)
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.entity_collection import EntityCollection as EntityCollection
from office365.sharepoint.principal.users.user import User as User

class UserCollection(EntityCollection[User]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def add_user(self, user): ...
    def get_by_principal_name(self, value: str) -> User: ...
    def get_by_email(self, email): ...
    def get_by_id(self, user_id): ...
    def get_by_login_name(self, login_name): ...
    def remove_by_id(self, user_id): ...
    def remove_by_login_name(self, login_name): ...
