from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.alerts.collection import AlertCollection as AlertCollection
from office365.sharepoint.principal.principal import Principal as Principal
from office365.sharepoint.principal.users.id_info import UserIdInfo as UserIdInfo
from office365.sharepoint.userprofiles.person_properties import (
    PersonProperties as PersonProperties,
)

class User(Principal):
    def get_personal_site(self): ...
    def get_recent_files(self, top: int = 100): ...
    def get_user_profile_properties(self, property_names: Incomplete | None = None): ...
    def expire(self): ...
    @property
    def aad_object_id(self): ...
    @property
    def alerts(self): ...
    @property
    def groups(self): ...
    @property
    def is_site_admin(self) -> bool | None: ...
    @property
    def user_id(self): ...
    @property
    def email(self) -> str | None: ...
    @property
    def email_with_fallback(self) -> str | None: ...
    @property
    def expiration(self) -> str | None: ...
    @property
    def is_email_authentication_guest_user(self) -> bool | None: ...
    @property
    def is_share_by_email_guest_user(self) -> bool | None: ...
    @property
    def user_principal_name(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
