from datetime import datetime

from office365.sharepoint.entity import Entity as Entity

class WebInformation(Entity):
    @property
    def configuration(self) -> str | None: ...
    @property
    def created(self) -> datetime | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def id(self) -> str | None: ...
    @property
    def language(self) -> int | None: ...
    @property
    def last_item_modified_date(self) -> datetime | None: ...
    @property
    def server_relative_url(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def web_template(self) -> str | None: ...
    @property
    def web_template_id(self) -> int | None: ...
