from _typeshed import Incomplete
from datetime import datetime
from pydantic import StrictInt as StrictInt, StrictStr as StrictStr, validate_arguments
from qualer_sdk.api_client import ApiClient as ApiClient
from qualer_sdk.api_response import ApiResponse as ApiResponse
from qualer_sdk.exceptions import ApiTypeError as ApiTypeError, ApiValueError as ApiValueError
from qualer_sdk.models.qualer_api_models_asset_service_records_from_add_asset_service_record_model import QualerApiModelsAssetServiceRecordsFromAddAssetServiceRecordModel as QualerApiModelsAssetServiceRecordsFromAddAssetServiceRecordModel
from qualer_sdk.models.qualer_api_models_asset_service_records_from_update_asset_service_record_model import QualerApiModelsAssetServiceRecordsFromUpdateAssetServiceRecordModel as QualerApiModelsAssetServiceRecordsFromUpdateAssetServiceRecordModel
from qualer_sdk.models.qualer_api_models_asset_service_records_to_asset_service_record_response_model import QualerApiModelsAssetServiceRecordsToAssetServiceRecordResponseModel as QualerApiModelsAssetServiceRecordsToAssetServiceRecordResponseModel

class AssetServiceRecordsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    @validate_arguments
    def add_asset_service_record(self, asset_id: StrictInt, model: QualerApiModelsAssetServiceRecordsFromAddAssetServiceRecordModel, **kwargs) -> object: ...
    @validate_arguments
    def add_asset_service_record_with_http_info(self, asset_id: StrictInt, model: QualerApiModelsAssetServiceRecordsFromAddAssetServiceRecordModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def document_list(self, asset_service_record_id2: StrictStr, asset_service_record_id: StrictStr | None = None, model_asset_service_record_id: StrictInt | None = None, **kwargs) -> list[str]: ...
    @validate_arguments
    def document_list_with_http_info(self, asset_service_record_id2: StrictStr, asset_service_record_id: StrictStr | None = None, model_asset_service_record_id: StrictInt | None = None, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def download_document(self, asset_service_record_id2: StrictStr, file_name2: StrictStr, asset_service_record_id: StrictStr | None = None, file_name: StrictStr | None = None, model_asset_service_record_id: StrictInt | None = None, model_file_name: StrictStr | None = None, **kwargs) -> object: ...
    @validate_arguments
    def download_document_with_http_info(self, asset_service_record_id2: StrictStr, file_name2: StrictStr, asset_service_record_id: StrictStr | None = None, file_name: StrictStr | None = None, model_asset_service_record_id: StrictInt | None = None, model_file_name: StrictStr | None = None, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def download_documents(self, asset_service_record_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def download_documents_with_http_info(self, asset_service_record_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_asset_service_record(self, asset_service_record_id: StrictStr, model_asset_service_record_id: StrictInt | None = None, **kwargs) -> QualerApiModelsAssetServiceRecordsToAssetServiceRecordResponseModel: ...
    @validate_arguments
    def get_asset_service_record_with_http_info(self, asset_service_record_id: StrictStr, model_asset_service_record_id: StrictInt | None = None, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_asset_service_records(self, model_asset_id: StrictInt | None = None, model_serial_number: StrictStr | None = None, model_from: datetime | None = None, model_to: datetime | None = None, **kwargs) -> QualerApiModelsAssetServiceRecordsToAssetServiceRecordResponseModel: ...
    @validate_arguments
    def get_asset_service_records_with_http_info(self, model_asset_id: StrictInt | None = None, model_serial_number: StrictStr | None = None, model_from: datetime | None = None, model_to: datetime | None = None, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_asset_service_records_by_asset(self, asset_id: StrictInt, **kwargs) -> list[QualerApiModelsAssetServiceRecordsToAssetServiceRecordResponseModel]: ...
    @validate_arguments
    def get_asset_service_records_by_asset_with_http_info(self, asset_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def update_asset_service_record(self, asset_service_record_id: StrictInt, model: QualerApiModelsAssetServiceRecordsFromUpdateAssetServiceRecordModel, **kwargs) -> object: ...
    @validate_arguments
    def update_asset_service_record_with_http_info(self, asset_service_record_id: StrictInt, model: QualerApiModelsAssetServiceRecordsFromUpdateAssetServiceRecordModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def upload_documents(self, asset_service_record_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def upload_documents_with_http_info(self, asset_service_record_id: StrictInt, **kwargs) -> ApiResponse: ...
