from _typeshed import Incomplete
from datetime import datetime
from pydantic import Field as Field, StrictInt as StrictInt, StrictStr as StrictStr, validate_arguments
from qualer_sdk.api_client import ApiClient as ApiClient
from qualer_sdk.api_response import ApiResponse as ApiResponse
from qualer_sdk.exceptions import ApiTypeError as ApiTypeError, ApiValueError as ApiValueError
from qualer_sdk.models.qualer_api_models_service_orders_from_add_work_items_model import QualerApiModelsServiceOrdersFromAddWorkItemsModel as QualerApiModelsServiceOrdersFromAddWorkItemsModel
from qualer_sdk.models.qualer_api_models_service_orders_from_item_charge_update_model import QualerApiModelsServiceOrdersFromItemChargeUpdateModel as QualerApiModelsServiceOrdersFromItemChargeUpdateModel
from qualer_sdk.models.qualer_api_models_service_orders_from_order_item_update_model import QualerApiModelsServiceOrdersFromOrderItemUpdateModel as QualerApiModelsServiceOrdersFromOrderItemUpdateModel
from qualer_sdk.models.qualer_api_models_service_orders_to_asset_add_result_response_model import QualerApiModelsServiceOrdersToAssetAddResultResponseModel as QualerApiModelsServiceOrdersToAssetAddResultResponseModel
from qualer_sdk.models.qualer_api_models_service_orders_to_client_order_item_response_model import QualerApiModelsServiceOrdersToClientOrderItemResponseModel as QualerApiModelsServiceOrdersToClientOrderItemResponseModel
from typing_extensions import Annotated

class ServiceOrderItemsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    @validate_arguments
    def add_work_items(self, service_order_id: StrictInt, model: QualerApiModelsServiceOrdersFromAddWorkItemsModel, **kwargs) -> QualerApiModelsServiceOrdersToAssetAddResultResponseModel: ...
    @validate_arguments
    def add_work_items_with_http_info(self, service_order_id: StrictInt, model: QualerApiModelsServiceOrdersFromAddWorkItemsModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def delete_work_item_image(self, work_item_id: StrictInt, image_name: StrictStr, **kwargs) -> object: ...
    @validate_arguments
    def delete_work_item_image_with_http_info(self, work_item_id: StrictInt, image_name: StrictStr, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_item(self, work_item_id: StrictInt, **kwargs) -> QualerApiModelsServiceOrdersToClientOrderItemResponseModel: ...
    @validate_arguments
    def get_work_item_with_http_info(self, work_item_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_item_charges(self, work_item_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def get_work_item_charges_with_http_info(self, work_item_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_item_image(self, work_item_id: StrictInt, image_name: StrictStr, **kwargs) -> object: ...
    @validate_arguments
    def get_work_item_image_with_http_info(self, work_item_id: StrictInt, image_name: StrictStr, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_item_images(self, work_item_id: StrictInt, **kwargs) -> list[str]: ...
    @validate_arguments
    def get_work_item_images_with_http_info(self, work_item_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_items(self, service_order_id: StrictInt, **kwargs) -> list[QualerApiModelsServiceOrdersToClientOrderItemResponseModel]: ...
    @validate_arguments
    def get_work_items_with_http_info(self, service_order_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_items_workitems(self, status: Annotated[StrictStr | None, None] = None, company_id: Annotated[StrictInt | None, None] = None, var_from: Annotated[datetime | None, None] = None, to: Annotated[datetime | None, None] = None, work_item_number: Annotated[StrictStr | None, None] = None, asset_search: Annotated[StrictStr | None, None] = None, **kwargs) -> list[QualerApiModelsServiceOrdersToClientOrderItemResponseModel]: ...
    @validate_arguments
    def get_work_items_workitems_with_http_info(self, status: Annotated[StrictStr | None, None] = None, company_id: Annotated[StrictInt | None, None] = None, var_from: Annotated[datetime | None, None] = None, to: Annotated[datetime | None, None] = None, work_item_number: Annotated[StrictStr | None, None] = None, asset_search: Annotated[StrictStr | None, None] = None, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def put_charges(self, work_item_id: StrictInt, model: QualerApiModelsServiceOrdersFromItemChargeUpdateModel, **kwargs) -> object: ...
    @validate_arguments
    def put_charges_with_http_info(self, work_item_id: StrictInt, model: QualerApiModelsServiceOrdersFromItemChargeUpdateModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def set_work_item(self, work_item_id: StrictInt, model: QualerApiModelsServiceOrdersFromOrderItemUpdateModel, **kwargs) -> object: ...
    @validate_arguments
    def set_work_item_with_http_info(self, work_item_id: StrictInt, model: QualerApiModelsServiceOrdersFromOrderItemUpdateModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def upload_work_item_images(self, work_item_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def upload_work_item_images_with_http_info(self, work_item_id: StrictInt, **kwargs) -> ApiResponse: ...
