from _typeshed import Incomplete
from pydantic import StrictInt as StrictInt, validate_arguments
from qualer_sdk.api_client import ApiClient as ApiClient
from qualer_sdk.api_response import ApiResponse as ApiResponse
from qualer_sdk.exceptions import ApiTypeError as ApiTypeError, ApiValueError as ApiValueError
from qualer_sdk.models.qualer_api_models_service_orders_from_service_order_metadata_create_model import QualerApiModelsServiceOrdersFromServiceOrderMetadataCreateModel as QualerApiModelsServiceOrdersFromServiceOrderMetadataCreateModel
from qualer_sdk.models.qualer_api_models_service_orders_from_service_order_metadata_update_model import QualerApiModelsServiceOrdersFromServiceOrderMetadataUpdateModel as QualerApiModelsServiceOrdersFromServiceOrderMetadataUpdateModel

class ServiceOrderMetadataApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    @validate_arguments
    def create_post2(self, service_order_id: StrictInt, model: QualerApiModelsServiceOrdersFromServiceOrderMetadataCreateModel, **kwargs) -> object: ...
    @validate_arguments
    def create_post2_with_http_info(self, service_order_id: StrictInt, model: QualerApiModelsServiceOrdersFromServiceOrderMetadataCreateModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def delete_delete2(self, service_order_id: StrictInt, service_order_metadata_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def delete_delete2_with_http_info(self, service_order_id: StrictInt, service_order_metadata_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_get6(self, service_order_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def get_get6_with_http_info(self, service_order_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def update_put2(self, service_order_id: StrictInt, model: QualerApiModelsServiceOrdersFromServiceOrderMetadataUpdateModel, **kwargs) -> object: ...
    @validate_arguments
    def update_put2_with_http_info(self, service_order_id: StrictInt, model: QualerApiModelsServiceOrdersFromServiceOrderMetadataUpdateModel, **kwargs) -> ApiResponse: ...
