from _typeshed import Incomplete
from pydantic import StrictInt as StrictInt, validate_arguments
from qualer_sdk.api_client import ApiClient as ApiClient
from qualer_sdk.api_response import ApiResponse as ApiResponse
from qualer_sdk.exceptions import ApiTypeError as ApiTypeError, ApiValueError as ApiValueError
from qualer_sdk.models.qualer_api_models_service_orders_to_service_order_part_repair_response import QualerApiModelsServiceOrdersToServiceOrderPartRepairResponse as QualerApiModelsServiceOrdersToServiceOrderPartRepairResponse
from qualer_sdk.models.qualer_web_mvc_areas_api_models_service_orders_from_service_order_part_repair_create_model import QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairCreateModel as QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairCreateModel
from qualer_sdk.models.qualer_web_mvc_areas_api_models_service_orders_from_service_order_part_repair_update_model import QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairUpdateModel as QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairUpdateModel

class ServiceOrderPartsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    @validate_arguments
    def create_work_order_parts(self, service_order_id: StrictInt, model: QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairCreateModel, **kwargs) -> object: ...
    @validate_arguments
    def create_work_order_parts_with_http_info(self, service_order_id: StrictInt, model: QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairCreateModel, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def delete_work_order_task(self, service_order_id: StrictInt, service_order_item_part_id: StrictInt, **kwargs) -> object: ...
    @validate_arguments
    def delete_work_order_task_with_http_info(self, service_order_id: StrictInt, service_order_item_part_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def get_work_order_parts(self, service_order_id: StrictInt, **kwargs) -> list[QualerApiModelsServiceOrdersToServiceOrderPartRepairResponse]: ...
    @validate_arguments
    def get_work_order_parts_with_http_info(self, service_order_id: StrictInt, **kwargs) -> ApiResponse: ...
    @validate_arguments
    def update_work_order_parts(self, service_order_id: StrictInt, model: QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairUpdateModel, **kwargs) -> object: ...
    @validate_arguments
    def update_work_order_parts_with_http_info(self, service_order_id: StrictInt, model: QualerWebMvcAreasApiModelsServiceOrdersFromServiceOrderPartRepairUpdateModel, **kwargs) -> ApiResponse: ...
