from office365.sharepoint.entity import Entity as Entity

class WebPart(Entity):
    @property
    def export_mode(self) -> int | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def title_url(self) -> str | None: ...
    @property
    def zone_index(self) -> int | None: ...
    @property
    def entity_type_name(self): ...
