from office365.entity import Entity as Entity
from office365.onedrive.workbooks.ranges.range import WorkbookRange as WorkbookRange
from office365.onedrive.workbooks.tables.columns.collection import WorkbookTableColumnCollection as WorkbookTableColumnCollection
from office365.onedrive.workbooks.tables.rows.collection import WorkbookTableRowCollection as WorkbookTableRowCollection
from office365.onedrive.workbooks.tables.sort import WorkbookTableSort as WorkbookTableSort
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.function import FunctionQuery as FunctionQuery
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery

class WorkbookTable(Entity):
    def data_body_range(self): ...
    def range(self): ...
    def total_row_range(self): ...
    def clear_filters(self): ...
    def reapply_filters(self): ...
    @property
    def highlight_first_column(self) -> bool | None: ...
    @property
    def highlight_last_column(self) -> bool | None: ...
    @property
    def legacy_id(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def show_banded_columns(self) -> bool | None: ...
    @property
    def show_banded_rows(self) -> bool | None: ...
    @property
    def show_filter_button(self) -> bool | None: ...
    @property
    def show_headers(self) -> bool | None: ...
    @property
    def columns(self) -> WorkbookTableColumnCollection: ...
    @property
    def rows(self) -> WorkbookTableRowCollection: ...
    @property
    def sort(self) -> WorkbookTableSort: ...
    @property
    def worksheet(self): ...
