from office365.entity import Entity as Entity
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery

class GroupLifecyclePolicy(Entity):
    def add_group(self, group_id): ...
    def remove_group(self, group_id: str) -> ClientResult[bool]: ...
    @property
    def alternate_notification_emails(self) -> str | None: ...
    @property
    def group_lifetime_in_days(self) -> int | None: ...
    @property
    def managed_group_types(self) -> str | None: ...
