from office365.runtime.odata.json_format import ODataJsonFormat as ODataJsonFormat
from office365.runtime.odata.v4.metadata_level import (
    ODataV4MetadataLevel as ODataV4MetadataLevel,
)

class V4JsonFormat(ODataJsonFormat):
    IEEE754Compatible: bool
    streaming: bool
    def __init__(self, metadata_level=...) -> None: ...
    @property
    def metadata_type(self): ...
    @property
    def value_tag(self): ...
    @property
    def collection(self): ...
    @property
    def collection_next(self): ...
    @property
    def collection_delta(self): ...
    @property
    def etag(self): ...
    @property
    def media_type(self): ...
    @property
    def include_control_information(self): ...
