from datetime import datetime

from office365.directory.object import DirectoryObject as DirectoryObject

class AppRoleAssignment(DirectoryObject):
    @property
    def app_role_id(self) -> str | None: ...
    @property
    def created_datetime(self) -> datetime: ...
    @property
    def principal_display_name(self) -> str | None: ...
    @property
    def principal_id(self) -> str | None: ...
    @property
    def principal_type(self) -> str | None: ...
    @property
    def resource_display_name(self) -> str | None: ...
    @property
    def resource_id(self) -> str | None: ...
