from office365.runtime.client_value import ClientValue as ClientValue

class RenderListDataOverrideParameters(ClientValue):
    def __init__(self) -> None: ...
    @property
    def entity_type_name(self): ...
