class ListTemplateType:
    def __init__(self) -> None: ...
    InvalidType: int
    NoListTemplate: int
    GenericList: int
    DocumentLibrary: int
    Survey: int
    Links: int
    Announcements: int
    Contacts: int
    Events: int
    Tasks: int
    DiscussionBoard: int
    PictureLibrary: int
    DataSources: int
    WebTemplateCatalog: int
    UserInformation: int
    WebPartCatalog: int
    ListTemplateCatalog: int
    XMLForm: int
    MasterPageCatalog: int
    NoCodeWorkflows: int
    WorkflowProcess: int
    WebPageLibrary: int
    CustomGrid: int
    SolutionCatalog: int
    NoCodePublic: int
    ThemeCatalog: int
    DesignCatalog: int
    AppDataCatalog: int
    DataConnectionLibrary: int
    WorkflowHistory: int
    GanttTasks: int
    HelpLibrary: int
    AccessRequest: int
    TasksWithTimelineAndHierarchy: int
    MaintenanceLogs: int
    Meetings: int
    Agenda: int
    MeetingUser: int
    Decision: int
    MeetingObjective: int
    TextBox: int
    ThingsToBring: int
    HomePageLibrary: int
    Posts: int
    Comments: int
    Categories: int
    Facility: int
    Whereabouts: int
    CallTrack: int
    Circulation: int
    Timecard: int
    Holidays: int
    IMEDic: int
