from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.client_value_collection import ClientValueCollection as ClientValueCollection
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.principal.groups.collection import GroupCollection as GroupCollection
from office365.sharepoint.principal.principal import Principal as Principal
from office365.sharepoint.utilities.principal_info import PrincipalInfo as PrincipalInfo

class Group(Principal):
    def delete_object(self): ...
    def expand_to_principals(self, max_count: int = 10): ...
    def set_user_as_owner(self, user): ...
    @property
    def parent_collection(self) -> GroupCollection: ...
    @property
    def allow_members_edit_membership(self) -> bool | None: ...
    @property
    def allow_request_to_join_leave(self) -> bool | None: ...
    @property
    def auto_accept_request_to_join_leave(self) -> bool | None: ...
    @property
    def can_current_user_edit_membership(self) -> bool | None: ...
    @property
    def can_current_user_manage_group(self) -> bool | None: ...
    @property
    def can_current_user_view_membership(self) -> bool | None: ...
    @property
    def only_allow_members_view_membership(self) -> bool | None: ...
    @property
    def owner_title(self) -> str | None: ...
    @property
    def request_to_join_leave_email_setting(self) -> str | None: ...
    @property
    def owner(self): ...
    @property
    def users(self): ...
