from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.principal.users.user import User as User
from office365.sharepoint.recyclebin.item_collection import RecycleBinItemCollection as RecycleBinItemCollection
from office365.sharepoint.types.resource_path import ResourcePath as SPResPath

class RecycleBinItem(Entity):
    def restore(self): ...
    def move_to_second_stage(self): ...
    @property
    def author_email(self) -> str | None: ...
    @property
    def author_name(self) -> str | None: ...
    @property
    def deleted_by_email(self) -> str | None: ...
    @property
    def deleted_by_name(self) -> str | None: ...
    @property
    def deleted_date_local_formatted(self) -> str | None: ...
    @property
    def dir_name(self) -> str | None: ...
    @property
    def dir_name_path(self) -> SPResPath | None: ...
    @property
    def item_state(self) -> int | None: ...
    @property
    def item_type(self) -> int | None: ...
    @property
    def id(self) -> str | None: ...
    @property
    def leaf_name(self) -> str | None: ...
    @property
    def leaf_name_path(self) -> SPResPath | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def author(self): ...
    @property
    def deleted_by(self): ...
    @property
    def deleted_date(self): ...
    @property
    def parent_collection(self) -> RecycleBinItemCollection: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True) -> None: ...
