from _typeshed import Incomplete
from office365.azure_env import AzureEnvironment as AzureEnvironment
from office365.runtime.auth.token_response import TokenResponse as TokenResponse

class AuthenticationContext:
    def __init__(
        self,
        tenant: Incomplete | None = None,
        scopes: Incomplete | None = None,
        token_cache: Incomplete | None = None,
        environment=...,
    ) -> None: ...
    def acquire_token(self) -> TokenResponse: ...
    def with_access_token(self, token_callback): ...
    def with_certificate(self, client_id, thumbprint, private_key): ...
    def with_client_secret(
        self, client_id: str, client_secret: str
    ) -> AuthenticationContext: ...
    def with_token_interactive(
        self, client_id: str, username: str | None = None
    ) -> AuthenticationContext: ...
    def with_username_and_password(
        self, client_id: str, username: str, password: str
    ) -> AuthenticationContext: ...
    @property
    def authority_url(self): ...
