from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.social.thread import SocialThread as SocialThread

class SocialRestThread(Entity):
    def __init__(self, context) -> None: ...
    def like(self, post_id): ...
    def unlike(self, post_id): ...
    @property
    def social_thread(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
