from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.directory.user import User as User
from office365.sharepoint.entity import Entity as Entity

class DirectorySession(Entity):
    def __init__(self, context) -> None: ...
    @property
    def me(self): ...
    def get_graph_user(self, principal_name): ...
    def get_sharepoint_data_for_user(self, user_id): ...
    @property
    def entity_type_name(self): ...
