from office365.azure_env import AzureEnvironment as AzureEnvironment
from office365.runtime.compat import timezone as timezone
from office365.runtime.compat import urlparse as urlparse

class STSProfile:
    def __init__(self, site_url: str, environment: str = None) -> None: ...
    def reset(self) -> None: ...
    @property
    def tenant(self): ...
    @property
    def security_token_service_url(self): ...
    @property
    def signin_page_url(self): ...
    @property
    def user_realm_service_url(self): ...
    @property
    def token_issuer(self): ...
    @property
    def created(self): ...
    @property
    def expires(self): ...
    @property
    def site_url(self): ...
