from office365.directory.object import DirectoryObject as DirectoryObject
from office365.runtime.types.collections import StringCollection as StringCollection

class ExtensionProperty(DirectoryObject):
    @property
    def name(self) -> str | None: ...
    @property
    def app_display_name(self) -> str | None: ...
    @property
    def data_type(self) -> str | None: ...
    @property
    def target_objects(self): ...
