from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.principal.principal import Principal as Principal
from office365.sharepoint.principal.users.user import User as User

class ObjectSharingInformationUser(Entity):
    @property
    def email(self) -> str | None: ...
    @property
    def sip_address(self) -> str | None: ...
    @property
    def login_name(self) -> str | None: ...
    def principal(self): ...
    def user(self): ...
