from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.sharing.object_sharing_information import (
    ObjectSharingInformation as ObjectSharingInformation,
)
from office365.sharepoint.sharing.permission_information import (
    SharingPermissionInformation as SharingPermissionInformation,
)
from office365.sharepoint.sharing.sharepoint_sharing_settings import (
    SharePointSharingSettings as SharePointSharingSettings,
)

class ObjectSharingSettings(Entity):
    @property
    def web_url(self) -> str | None: ...
    @property
    def access_request_mode(self) -> bool | None: ...
    @property
    def block_people_picker_and_sharing(self) -> bool | None: ...
    @property
    def can_current_user_manage_organization_readonly_link(self) -> bool | None: ...
    @property
    def can_current_user_manage_organization_read_write_link(self) -> bool | None: ...
    @property
    def can_current_user_manage_readonly_link(self) -> bool | None: ...
    @property
    def can_send_email(self) -> bool | None: ...
    @property
    def can_send_link(self) -> bool | None: ...
    @property
    def is_user_site_admin(self) -> bool | None: ...
    @property
    def list_id(self) -> str | None: ...
    @property
    def roles(self): ...
    @property
    def object_sharing_information(self): ...
    @property
    def sharepoint_settings(self): ...
    @property
    def sharing_permissions(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
