from office365.azure_env import AzureEnvironment as AzureEnvironment
from office365.runtime.auth.entra.authentication_context import (
    AuthenticationContext as AuthenticationContext,
)
from office365.runtime.http.request_options import RequestOptions as RequestOptions
from office365.runtime.odata.request import ODataRequest as ODataRequest
from office365.runtime.odata.v4.json_format import V4JsonFormat as V4JsonFormat
from typing import Callable

class GraphRequest(ODataRequest):
    def __init__(
        self, version: str = "v1.0", tenant: str = None, environment: str = ...
    ) -> None: ...
    def with_access_token(self, token_callback: Callable[[], dict]) -> GraphRequest: ...
    def with_certificate(
        self, client_id: str, thumbprint: str, private_key: str
    ) -> GraphRequest: ...
    def with_client_secret(
        self, client_id: str, client_secret: str
    ) -> GraphRequest: ...
    def with_token_interactive(
        self, client_id: str, username: str | None = None
    ) -> GraphRequest: ...
    def with_username_and_password(
        self, client_id: str, username: str, password: str
    ) -> GraphRequest: ...
    def authenticate_request(self, request: RequestOptions) -> None: ...
    @property
    def service_root_url(self) -> str: ...
