from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.sites.language_collection import LanguageCollection as LanguageCollection
from office365.sharepoint.webs.time_zone import TimeZone as TimeZone, TimeZoneCollection as TimeZoneCollection

class RegionalSettings(Entity):
    @property
    def adjust_hijri_days(self) -> int | None: ...
    @property
    def alternate_calendar_type(self) -> int | None: ...
    @property
    def am(self) -> str | None: ...
    @property
    def calendar_type(self) -> int | None: ...
    @property
    def collation(self) -> int | None: ...
    @property
    def collation_lcid(self) -> int | None: ...
    @property
    def date_format(self) -> int | None: ...
    @property
    def date_separator(self) -> str | None: ...
    @property
    def decimal_separator(self) -> str | None: ...
    @property
    def digit_grouping(self) -> str | None: ...
    @property
    def first_day_of_week(self) -> int | None: ...
    @property
    def first_week_of_year(self) -> int | None: ...
    @property
    def is_east_asia(self) -> bool | None: ...
    @property
    def is_right_to_left(self) -> bool | None: ...
    @property
    def is_ui_right_to_left(self) -> bool | None: ...
    @property
    def list_separator(self) -> str | None: ...
    @property
    def locale_id(self) -> int | None: ...
    @property
    def negative_sign(self) -> str | None: ...
    @property
    def neg_number_mode(self) -> int | None: ...
    @property
    def pm(self) -> str | None: ...
    @property
    def positive_sign(self) -> str | None: ...
    @property
    def show_weeks(self) -> bool | None: ...
    @property
    def thousand_separator(self) -> str | None: ...
    @property
    def work_days(self) -> int | None: ...
    @property
    def time_zone(self): ...
    @property
    def time_zones(self): ...
    @property
    def installed_languages(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
