from office365.sharepoint.entity import Entity as Entity

class WebTemplate(Entity):
    @property
    def description(self) -> str | None: ...
    @property
    def display_category(self) -> str | None: ...
    @property
    def image_url(self) -> str | None: ...
    @property
    def is_hidden(self) -> bool | None: ...
    @property
    def is_root_web_only(self) -> bool | None: ...
    @property
    def is_sub_web_only(self) -> bool | None: ...
    @property
    def lcid(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
