from _typeshed import Incomplete
from office365.delta_collection import DeltaCollection as DeltaCollection
from office365.directory.applications.application import Application as Application
from office365.directory.serviceprincipals.service_principal import (
    ServicePrincipal as ServicePrincipal,
)
from office365.runtime.paths.appid import AppIdPath as AppIdPath

class ServicePrincipalCollection(DeltaCollection[ServicePrincipal]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def add(self, app_id): ...
    def get_by_app_id(self, app_id): ...
    def get_by_app(self, app: str | Application) -> ServicePrincipal: ...
    def get_by_name(self, name: str) -> ServicePrincipal: ...
