from datetime import datetime

from office365.runtime.types.collections import StringCollection as StringCollection
from office365.sharepoint.entity import Entity as Entity

class DlpPolicyTip(Entity):
    @property
    def applied_actions_text(self) -> str | None: ...
    @property
    def compliance_url(self) -> str | None: ...
    @property
    def general_text(self) -> str | None: ...
    @property
    def last_processed_time(self) -> datetime | None: ...
    @property
    def matched_condition_descriptions(self): ...
    @property
    def override_options(self): ...
    @property
    def two_letter_iso_language_name(self) -> str | None: ...
