from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.runtime.types.collections import StringCollection as StringCollection

class DirectoryObject(Entity):
    def check_member_objects(self, ids: Incomplete | None = None): ...
    def get_member_objects(self, security_enabled_only: bool = True): ...
    def get_member_groups(self, security_enabled_only: bool = True): ...
    def check_member_groups(self, group_ids: Incomplete | None = None): ...
    def restore(self): ...
    @property
    def deleted_datetime(self): ...
