from office365.entity_collection import EntityCollection as EntityCollection
from office365.onedrive.listitems.list_item import ListItem as ListItem
from office365.runtime.http.request_options import RequestOptions as RequestOptions

class ListItemCollection(EntityCollection[ListItem]):
    def __init__(self, context, resource_path) -> None: ...
    def honor_nonindexed(self, value: bool) -> ListItemCollection: ...
    def get(self): ...
    def get_by_name(self, name): ...
    def get_by_path(self, path): ...
