import datetime
from office365.sharepoint.entity import Entity as Entity

class StorageMetrics(Entity):
    @property
    def additional_file_stream_size(self) -> int | None: ...
    @property
    def last_modified(self) -> datetime.datetime | None: ...
    @property
    def total_file_count(self) -> int | None: ...
    @property
    def total_file_stream_size(self) -> int | None: ...
    @property
    def total_size(self) -> int | None: ...
    @property
    def version_count(self) -> int | None: ...
    @property
    def version_size(self) -> int | None: ...
