from office365.sharepoint.entity import Entity as Entity

class HubSite(Entity):
    @property
    def id(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def site_url(self) -> str | None: ...
    @property
    def targets(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def tenant_instance_id(self) -> str | None: ...
