from _typeshed import Incomplete
from office365.directory.permissions.grants.resource_specific import ResourceSpecificPermissionGrant as ResourceSpecificPermissionGrant
from office365.entity import Entity as Entity
from office365.entity_collection import EntityCollection as EntityCollection
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.teams.apps.installation import TeamsAppInstallation as TeamsAppInstallation
from office365.teams.channels.channel import Channel as Channel
from office365.teams.channels.collection import ChannelCollection as ChannelCollection
from office365.teams.fun_settings import TeamFunSettings as TeamFunSettings
from office365.teams.guest_settings import TeamGuestSettings as TeamGuestSettings
from office365.teams.members.settings import TeamMemberSettings as TeamMemberSettings
from office365.teams.messaging_settings import TeamMessagingSettings as TeamMessagingSettings
from office365.teams.operations.async_operation import TeamsAsyncOperation as TeamsAsyncOperation
from office365.teams.schedule.schedule import Schedule as Schedule
from office365.teams.summary import TeamSummary as TeamSummary
from office365.teams.teamwork.tags.tag import TeamworkTag as TeamworkTag
from office365.teams.template import TeamsTemplate as TeamsTemplate

class Team(Entity):
    def execute_query_and_wait(self): ...
    def delete_object(self): ...
    @property
    def fun_settings(self): ...
    @property
    def member_settings(self): ...
    @property
    def guest_settings(self): ...
    @property
    def messaging_settings(self): ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def classification(self) -> str | None: ...
    @property
    def is_archived(self) -> bool | None: ...
    @property
    def visibility(self): ...
    @property
    def web_url(self) -> str | None: ...
    @property
    def created_datetime(self): ...
    @property
    def all_channels(self) -> ChannelCollection: ...
    @property
    def incoming_channels(self) -> ChannelCollection: ...
    @property
    def channels(self) -> ChannelCollection: ...
    @property
    def group(self): ...
    @property
    def primary_channel(self) -> Channel: ...
    @property
    def schedule(self): ...
    @property
    def installed_apps(self) -> EntityCollection[TeamsAppInstallation]: ...
    @property
    def operations(self) -> EntityCollection[TeamsAsyncOperation]: ...
    @property
    def permission_grants(self) -> EntityCollection[ResourceSpecificPermissionGrant]: ...
    @property
    def summary(self): ...
    @property
    def tenant_id(self) -> str | None: ...
    @property
    def tags(self): ...
    @property
    def template(self): ...
    def archive(self): ...
    def unarchive(self): ...
    def clone(self): ...
    def send_activity_notification(self, topic, activity_type, chain_id, preview_text, template_parameters, recipient): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
