from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity

class ConnectionSettings(Entity):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    @property
    def authentication_mode(self) -> str | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def entity_type_name(self): ...
