from datetime import datetime

from office365.entity import Entity as Entity

class DataPolicyOperation(Entity):
    @property
    def completed_datetime(self) -> datetime: ...
    @property
    def progress(self) -> float | None: ...
    @property
    def status(self) -> str | None: ...
    @property
    def storage_location(self) -> str | None: ...
    @property
    def submitted_datetime(self) -> datetime: ...
    @property
    def user_id(self) -> str | None: ...
