from datetime import datetime
from office365.runtime.paths.service_operation import ServiceOperationPath as ServiceOperationPath
from office365.sharepoint.entity import Entity as Entity

class Subscription(Entity):
    @property
    def application_id(self) -> str | None: ...
    @property
    def notification_url(self) -> str | None: ...
    @notification_url.setter
    def notification_url(self, value: str) -> None: ...
    @property
    def expiration_datetime(self) -> datetime | None: ...
    @expiration_datetime.setter
    def expiration_datetime(self, value: datetime | str) -> None: ...
    def set_property(self, name, value, persist_changes: bool = True): ...
    @property
    def entity_type_name(self): ...
