from office365.outlook.mail.attachments.attachment import Attachment as Attachment
from typing import AnyStr

class FileAttachment(Attachment):
    @property
    def content_id(self) -> str | None: ...
    @property
    def content_location(self) -> str | None: ...
    @property
    def content_bytes(self) -> AnyStr | None: ...
    @content_bytes.setter
    def content_bytes(self, value) -> None: ...
