from _typeshed import Incomplete
from office365.runtime.paths.service_operation import ServiceOperationPath as ServiceOperationPath
from office365.sharepoint.entity_collection import EntityCollection as EntityCollection
from office365.sharepoint.listitems.listitem import ListItem as ListItem

class ListItemCollection(EntityCollection[ListItem]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def get_by_id(self, item_id): ...
    def get_by_string_id(self, s_id): ...
    def get_by_url(self, url): ...
