from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.runtime.types.collections import StringCollection as StringCollection
from office365.sharepoint.contenttypes.content_type_id import ContentTypeId as ContentTypeId
from office365.sharepoint.contenttypes.fieldlinks.collection import FieldLinkCollection as FieldLinkCollection
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.fields.collection import FieldCollection as FieldCollection
from office365.sharepoint.translation.user_resource import UserResource as UserResource

class ContentType(Entity):
    def reorder_fields(self, field_names): ...
    def update(self, update_children): ...
    @property
    def client_form_custom_formatter(self) -> str | None: ...
    @property
    def display_form_client_side_component_id(self) -> str | None: ...
    @property
    def display_form_client_side_component_properties(self) -> str | None: ...
    @property
    def display_form_template_name(self) -> str | None: ...
    @property
    def display_form_url(self) -> str | None: ...
    @property
    def edit_form_client_side_component_id(self) -> str | None: ...
    @property
    def edit_form_client_side_component_properties(self) -> str | None: ...
    @property
    def id(self): ...
    @property
    def scope(self) -> str | None: ...
    @property
    def sealed(self) -> bool | None: ...
    @property
    def string_id(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def new_form_client_side_component_properties(self) -> str | None: ...
    @property
    def new_form_url(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @description.setter
    def description(self, value: str) -> None: ...
    @property
    def description_resource(self): ...
    @property
    def document_template(self) -> str | None: ...
    @property
    def document_template_url(self) -> str | None: ...
    @property
    def edit_form_url(self) -> str | None: ...
    @property
    def group(self) -> str | None: ...
    @group.setter
    def group(self, value: str) -> None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def js_link(self) -> str | None: ...
    @property
    def read_only(self) -> bool | None: ...
    @property
    def name_resource(self): ...
    @property
    def schema_xml(self) -> str | None: ...
    @property
    def fields(self): ...
    @property
    def parent(self): ...
    @property
    def field_links(self): ...
    @property
    def property_ref_name(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
