import datetime
from _typeshed import Incomplete
from office365.runtime.types.collections import StringCollection as StringCollection
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.publishing.pages.metadata_collection import (
    SitePageMetadataCollection as SitePageMetadataCollection,
)
from office365.sharepoint.publishing.pages.version_info import (
    SitePageVersionInfo as SitePageVersionInfo,
)
from office365.sharepoint.publishing.user_info import UserInfo as UserInfo

class SitePageMetadata(Entity):
    @property
    def absolute_url(self) -> str | None: ...
    @property
    def author_byline(self): ...
    @property
    def created_by(self): ...
    @property
    def last_modified_by(self): ...
    @property
    def comments_disabled(self) -> bool | None: ...
    @property
    def banner_image_url(self) -> str | None: ...
    @banner_image_url.setter
    def banner_image_url(self, value: str) -> None: ...
    @property
    def content_type_id(self) -> str | None: ...
    @content_type_id.setter
    def content_type_id(self, value: str) -> None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def does_user_have_edit_permission(self) -> bool | None: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def first_published(self) -> datetime.datetime | None: ...
    @property
    def is_page_checked_out_to_current_user(self) -> bool | None: ...
    @property
    def version_info(self): ...
    @property
    def parent_collection(self) -> SitePageMetadataCollection: ...
    @property
    def topic_header(self) -> str | None: ...
    @property
    def entity_type_name(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
