from _typeshed import Incomplete
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.entity import Entity as Entity

class ViewFieldCollection(Entity):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> str: ...
    @property
    def schema_xml(self) -> str | None: ...
    @property
    def items(self) -> list[str] | None: ...
    def set_property(self, name, value, persist_changes: bool = False): ...
    def add_view_field(self, field_name): ...
    def move_view_field_to(self, name, index): ...
    def remove_all_view_fields(self): ...
    def remove_view_field(self, field_name): ...
    @property
    def entity_type_name(self): ...
