from _typeshed import Incomplete
from abc import ABCMeta

class ODataJsonFormat:
    metadata_level: Incomplete
    def __init__(self, metadata_level: str = None) -> None: ...
    __metaclass__ = ABCMeta
    @property
    def metadata_type(self) -> None: ...
    @property
    def collection(self) -> None: ...
    @property
    def collection_next(self) -> None: ...
    @property
    def collection_delta(self) -> None: ...
    @property
    def etag(self) -> None: ...
    @property
    def value_tag(self) -> None: ...
    @property
    def media_type(self) -> str: ...
    @property
    def include_control_information(self) -> bool: ...
