from _typeshed import Incomplete

epoch_1904: Incomplete
epoch_1900: Incomplete
epoch_1900_minus_1: Incomplete

class XLDateError(ValueError): ...
class XLDateNegative(XLDateError): ...
class XLDateAmbiguous(XLDateError): ...
class XLDateTooLarge(XLDateError): ...
class XLDateBadDatemode(XLDateError): ...
class XLDateBadTuple(XLDateError): ...

def xldate_as_tuple(xldate, datemode): ...
def xldate_as_datetime(xldate, datemode): ...
def xldate_from_date_tuple(date_tuple, datemode): ...
def xldate_from_time_tuple(time_tuple): ...
def xldate_from_datetime_tuple(datetime_tuple, datemode): ...
