from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class Relation(Entity):
    @property
    def from_term(self): ...
    @property
    def to_term(self): ...
    @property
    def set(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
