from collections import abc

from _typeshed import Incomplete

def deepupdate(original, update): ...
def remove_none(mapping): ...
def resolve_schema_instance(schema): ...
def get_appcontext(): ...
def load_info_from_docstring(docstring, *, delimiter: str = "---"): ...
def unpack_tuple_response(rv): ...
def set_status_and_headers_in_response(response, status, headers) -> None: ...
def prepare_response(response, spec, content_type) -> None: ...
def normalize_config_prefix(config_prefix): ...

class PrefixedMappingProxy(abc.Mapping):
    prefix: Incomplete
    def __init__(self, proxied_dict, prefix) -> None: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
