from office365.entity import Entity as Entity

class WorkbookRangeBorder(Entity):
    @property
    def color(self) -> str | None: ...
    @property
    def side_index(self) -> str | None: ...
    @property
    def style(self) -> str | None: ...
    @property
    def weight(self) -> str | None: ...
