from office365.entity import Entity as Entity
from office365.onedrive.workbooks.functions.result import (
    WorkbookFunctionResult as WorkbookFunctionResult,
)
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)

class WorkbookFunctions(Entity):
    def abs(self, number): ...
    def accr_int(self, issue, first_interest, settlement, rate, par, frequency): ...
    def accr_int_m(self, issue, settlement, rate, par, basis): ...
    def days(self, start_date, end_date): ...
    def power(self, number, power): ...
