from .mex import Mex as Mex

SAML_TOKEN_TYPE_V1: str
SAML_TOKEN_TYPE_V2: str
WSS_SAML_TOKEN_PROFILE_V1_1: str
WSS_SAML_TOKEN_PROFILE_V2: str

def parse_response(body): ...
def parse_error(body): ...
def findall_content(xml_string, tag): ...
def parse_token_by_re(raw_response): ...
