from _typeshed import Incomplete
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.queries.function import FunctionQuery as FunctionQuery
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.internal.queries.upload_file import (
    create_upload_file_query as create_upload_file_query,
)
from typing import AnyStr, IO
from typing_extensions import Self

class Attachment(Entity):
    def download(self, file_object, use_path: bool = True): ...
    def get_content(self) -> ClientResult[AnyStr]: ...
    def recycle_object(self): ...
    def upload(self, file_object: IO, use_path: bool = True) -> Self: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def file_name_as_path(self): ...
    @property
    def server_relative_url(self) -> str | None: ...
    @property
    def server_relative_path(self): ...
    @property
    def property_ref_name(self): ...
    def set_property(self, name, value, persist_changes: bool = True) -> None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
