from _typeshed import Incomplete
from office365.entity_collection import EntityCollection as EntityCollection
from office365.onedrive.sitepages.site_page import SitePage as SitePage
from office365.onedrive.sitepages.title_area import TitleArea as TitleArea
from office365.runtime.http.request_options import RequestOptions as RequestOptions

class SitePageCollection(EntityCollection[SitePage]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def get(self): ...
    def get_by_name(self, name): ...
    def get_by_title(self, title): ...
    def add(self, title, page_layout: str = 'article'): ...
