from _typeshed import Incomplete
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.translation.user_resource import UserResource as UserResource

class NavigationNode(Entity):
    @property
    def children(self) -> NavigationNodeCollection: ...
    @property
    def title(self) -> str | None: ...
    @title.setter
    def title(self, value) -> None: ...
    @property
    def url(self) -> str | None: ...
    @url.setter
    def url(self, value: str) -> None: ...
    @property
    def is_visible(self) -> bool | None: ...
    @property
    def is_external(self) -> bool | None: ...
    @property
    def parent_collection(self) -> NavigationNodeCollection: ...
    @property
    def title_resource(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
