class NavigationProviderType:
    def __init__(self) -> None: ...
    SPNavigationProvider: str
    AdministrationQuickLaunchProvider: str
    SharedServicesQuickLaunchProvider: str
    GlobalNavSiteMapProvider: str
    CombinedNavSiteMapProvider: str
    CurrentNavSiteMapProvider: str
    CurrentNavSiteMapProviderNoEncode: str
    GlobalNavigation: str
    CurrentNavigation: str
    MySitePersonalQuickLaunchProvider: str
    MySiteHostTopNavigationProvider: str
    GlobalNavigationSwitchableProvider: str
    CurrentNavigationSwitchableProvider: str
    GlobalNavigationTaxonomyProvider: str
    CurrentNavigationTaxonomyProvider: str
    MySiteMapProvider: str
    MySiteLeftNavProvider: str
    MySiteDocumentStaticProvider: str
    MySiteSitesPageStaticProvider: str
    MySiteSubNavProvider: str
    EduTopNavProvider: str
    MySiteHostQuickLaunchProvider: str
