from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.entity import Entity as Entity

class CorporateCatalogAppMetadata(Entity):
    def deploy(self, skip_feature_deployment): ...
    def remove(self): ...
    def install(self): ...
    def uninstall(self): ...
    @property
    def aad_permissions(self) -> str | None: ...
    @property
    def app_catalog_version(self) -> str | None: ...
    @property
    def can_upgrade(self) -> bool | None: ...
    @property
    def is_client_side_solution(self) -> bool | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def id(self) -> str | None: ...
    @property
    def property_ref_name(self): ...
    @property
    def entity_type_name(self): ...
