from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.outlook.calendar.email_address import EmailAddress as EmailAddress
from office365.runtime.types.collections import StringCollection as StringCollection

class CalendarPermission(Entity):
    @property
    def allowed_roles(self): ...
    @property
    def email_address(self): ...
    @property
    def is_inside_organization(self) -> bool | None: ...
    @property
    def is_removable(self) -> bool | None: ...
    @property
    def role(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
