from office365.sharepoint.entity import Entity as Entity

class AppDetails(Entity):
    @property
    def eula_url(self) -> str | None: ...
    @property
    def privacy_url(self) -> str | None: ...
    @property
    def publisher(self) -> str | None: ...
    @property
    def short_description(self) -> str | None: ...
    @property
    def support_url(self) -> str | None: ...
    @property
    def entity_type_name(self): ...
