from _typeshed import Incomplete
from office365.runtime.paths.service_operation import (
    ServiceOperationPath as ServiceOperationPath,
)
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.permissions.base_permissions import (
    BasePermissions as BasePermissions,
)

class RoleDefinition(Entity):
    @property
    def base_permissions(self): ...
    @property
    def id(self) -> int | None: ...
    @property
    def role_type_kind(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value) -> None: ...
    @property
    def description(self) -> str | None: ...
    @description.setter
    def description(self, value) -> None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
