from datetime import datetime
from office365.entity import Entity as Entity
from office365.search.identity_set import IdentitySet as IdentitySet

class SearchAnswer(Entity):
    @property
    def description(self) -> str | None: ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def last_modified_by(self) -> IdentitySet: ...
    @property
    def last_modified_datetime(self) -> datetime | None: ...
    @property
    def web_url(self) -> str | None: ...
    @property
    def entity_type_name(self): ...
