from _typeshed import Incomplete
from office365.directory.authentication.methods.method import AuthenticationMethod as AuthenticationMethod
from office365.entity import Entity as Entity
from office365.entity_collection import EntityCollection as EntityCollection
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class Authentication(Entity):
    @property
    def email_methods(self): ...
    @property
    def fido2_methods(self): ...
    @property
    def microsoft_authenticator_methods(self): ...
    @property
    def phone_methods(self): ...
    @property
    def password_methods(self): ...
    @property
    def methods(self) -> EntityCollection[AuthenticationMethod]: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
