from office365.sharepoint.entity import Entity as Entity

class UploadStatus(Entity):
    @property
    def expected_content_range(self) -> str | None: ...
    @property
    def expiration_date_time(self) -> str | None: ...
    @property
    def upload_id(self) -> str | None: ...
    @property
    def property_ref_name(self): ...
    @property
    def entity_type_name(self): ...
