from _typeshed import Incomplete
from office365.directory.permissions.identity_set import IdentitySet as IdentitySet
from office365.onenote.entity_schema_object_model import OnenoteEntitySchemaObjectModel as OnenoteEntitySchemaObjectModel

class OnenoteEntityHierarchyModel(OnenoteEntitySchemaObjectModel):
    @property
    def display_name(self) -> str | None: ...
    @property
    def created_by(self) -> IdentitySet: ...
    @property
    def last_modified_by(self): ...
    @property
    def last_modified_datetime(self): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
