from _typeshed import Incomplete
from office365.entity_collection import EntityCollection as EntityCollection
from office365.onedrive.termstore.groups.group import Group as Group

class GroupCollection(EntityCollection[Group]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def add(self, display_name): ...
    def get_by_name(self, name: str) -> Group: ...
