from _typeshed import Incomplete
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.paths.service_operation import ServiceOperationPath as ServiceOperationPath
from office365.runtime.queries.create_entity import CreateEntityQuery as CreateEntityQuery
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.publishing.pages.metadata_collection import SitePageMetadataCollection as SitePageMetadataCollection
from office365.sharepoint.publishing.pages.page import SitePage as SitePage
from office365.sharepoint.translation.status_collection import TranslationStatusCollection as TranslationStatusCollection

class SitePageCollection(SitePageMetadataCollection[SitePage]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def add(self): ...
    def create_app_page(self, web_part_data: Incomplete | None = None): ...
    def get_translations(self, source_item_id: Incomplete | None = None): ...
    def is_site_page(self, url): ...
    def get_page_column_state(self, url): ...
    def get_by_url(self, url): ...
    def get_by_name(self, name): ...
    def templates(self): ...
    def update_full_page_app(self, server_relative_url, web_part_data_as_json): ...
