class PermissionKind:
    def __init__(self) -> None: ...
    EmptyMask: int
    ViewListItems: int
    AddListItems: int
    EditListItems: int
    DeleteListItems: int
    ApproveItems: int
    OpenItems: int
    ViewVersions: int
    DeleteVersions: int
    CancelCheckout: int
    ManagePersonalViews: int
    ManageLists: int
    ViewFormPages: int
    AnonymousSearchAccessList: int
    Open: int
    ViewPages: int
    AddAndCustomizePages: int
    ApplyThemeAndBorder: int
    ApplyStyleSheets: int
    ViewUsageData: int
    CreateSSCSite: int
    ManageSubwebs: int
    CreateGroups: int
    ManagePermissions: int
    BrowseDirectories: int
    BrowseUserInfo: int
    AddDelPrivateWebParts: int
    UpdatePersonalWebParts: int
    ManageWeb: int
    AnonymousSearchAccessWebLists: int
    UseClientIntegration: int
    UseRemoteAPIs: int
    ManageAlerts: int
    CreateAlerts: int
    EditMyUserInfo: int
    EnumeratePermissions: int
    FullMask: int
