from _typeshed import Incomplete
from datetime import datetime
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.runtime.queries.service_operation import ServiceOperationQuery as ServiceOperationQuery
from office365.sharepoint.entity import Entity as Entity
from office365.sharepoint.sites.site import Site as Site
from office365.sharepoint.userprofiles.followed_content import FollowedContent as FollowedContent

class UserProfile(Entity):
    @property
    def account_name(self) -> str | None: ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def follow_personal_site_url(self) -> str | None: ...
    @property
    def is_default_document_library_blocked(self) -> bool | None: ...
    @property
    def is_people_list_public(self) -> bool | None: ...
    @property
    def is_privacy_setting_on(self) -> bool | None: ...
    @property
    def is_self(self) -> bool | None: ...
    @property
    def job_title(self) -> str | None: ...
    @property
    def my_site_first_run_experience(self) -> int | None: ...
    @property
    def my_site_host_url(self) -> str | None: ...
    @property
    def o15_first_run_experience(self) -> int | None: ...
    @property
    def personal_site_capabilities(self) -> int | None: ...
    @property
    def personal_site_first_creation_error(self) -> str | None: ...
    @property
    def personal_site_first_creation_time(self) -> datetime | None: ...
    @property
    def picture_url(self) -> str | None: ...
    @property
    def public_url(self) -> str | None: ...
    @property
    def url_to_create_personal_site(self) -> str | None: ...
    @property
    def followed_content(self) -> FollowedContent: ...
    @property
    def personal_site(self) -> Site: ...
    def create_personal_site(self, lcid): ...
    def create_personal_site_enque(self, is_interactive): ...
    def set_my_site_first_run_experience(self, value): ...
    def share_all_social_data(self, share_all): ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
    def set_property(self, name, value, persist_changes: bool = True): ...
    @property
    def entity_type_name(self): ...
