import datetime
from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)

class Subscription(Entity):
    def reauthorize(self): ...
    @property
    def application_id(self) -> str | None: ...
    @property
    def change_type(self) -> str | None: ...
    @property
    def client_state(self) -> str | None: ...
    @property
    def creator_id(self) -> str | None: ...
    @property
    def encryption_certificate(self) -> str | None: ...
    @property
    def encryption_certificate_id(self) -> str | None: ...
    @property
    def expiration_datetime(self) -> datetime.datetime | None: ...
    @property
    def include_resource_data(self) -> bool | None: ...
    @property
    def latest_supported_tls_version(self) -> str | None: ...
    @property
    def lifecycle_notification_url(self) -> str | None: ...
    @property
    def notification_url(self) -> str | None: ...
    @property
    def resource(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
