from _typeshed import Incomplete
from office365.teams.schedule.change_request import (
    ScheduleChangeRequest as ScheduleChangeRequest,
)

class OfferShiftRequest(ScheduleChangeRequest):
    @property
    def recipient_action_datetime(self): ...
    @property
    def recipient_action_message(self) -> str | None: ...
    @property
    def recipient_user_id(self) -> str | None: ...
    @property
    def sender_shift_id(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
