from office365.runtime.client_request import ClientRequest as ClientRequest

class CsomRequest(ClientRequest):
    def process_response(self, response, query) -> None: ...
    def build_request(self, query) -> None: ...
