import datetime
from office365.entity import Entity as Entity

class AttachmentBase(Entity):
    @property
    def content_type(self) -> str | None: ...
    @property
    def last_modified_datetime(self) -> datetime.datetime | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def size(self) -> int | None: ...
