from office365.runtime.paths.resource_path import ResourcePath as ResourcePath
from office365.sharepoint.changes.change import Change as Change

class ChangeList(Change):
    @property
    def base_template(self) -> int | None: ...
    @property
    def editor(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def list_id(self) -> str | None: ...
    @property
    def creator(self): ...
