from office365.sharepoint.entity import Entity as Entity

class SiteCollectionAppCatalogAllowedItem(Entity):
    @property
    def site_id(self) -> str | None: ...
    @property
    def absolute_url(self) -> str | None: ...
    @property
    def property_ref_name(self): ...
    @property
    def entity_type_name(self): ...
