from _typeshed import Incomplete
from office365.runtime.paths.service_operation import (
    ServiceOperationPath as ServiceOperationPath,
)
from office365.runtime.queries.create_entity import (
    CreateEntityQuery as CreateEntityQuery,
)
from office365.runtime.queries.service_operation import (
    ServiceOperationQuery as ServiceOperationQuery,
)
from office365.sharepoint.entity_collection import EntityCollection as EntityCollection
from office365.sharepoint.lists.creation_information import (
    ListCreationInformation as ListCreationInformation,
)
from office365.sharepoint.lists.list import List as List

class ListCollection(EntityCollection[List]):
    def __init__(self, context, resource_path: Incomplete | None = None) -> None: ...
    def get_by_title(self, list_title: str) -> List: ...
    def get_by_id(self, list_id: str) -> List: ...
    def ensure_client_rendered_site_pages_library(self): ...
    def ensure_events_list(self): ...
    def ensure_site_assets_library(self): ...
    def ensure_site_pages_library(self): ...
    def add(self, list_creation_information: ListCreationInformation) -> List: ...
