from _typeshed import Incomplete
from datetime import timezone as timezone

is_py2: Incomplete
is_py3: Incomplete

def message_as_bytes_or_string(message): ...
def is_string_type(value): ...
def is_absolute_url(url): ...
def get_absolute_url(url): ...
def parse_query_string(url, key): ...
def get_mime_type(file_name): ...
