from office365.runtime.client_object import ClientObject as ClientObject
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class TaxonomyItem(ClientObject):
    @property
    def id(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def property_ref_name(self) -> str: ...
    def set_property(self, name, value, persist_changes: bool = True): ...
