from office365.sharepoint.fields.lookup import FieldLookup as FieldLookup

class FieldUser(FieldLookup):
    @property
    def presence(self) -> bool | None: ...
    @presence.setter
    def presence(self, val: bool) -> None: ...
    @property
    def allow_display(self) -> bool | None: ...
    @allow_display.setter
    def allow_display(self, val: bool) -> None: ...
    @property
    def selection_group(self) -> int | None: ...
    @selection_group.setter
    def selection_group(self, val: int) -> None: ...
