from _typeshed import Incomplete
from office365.directory.audit.signins.location import SignInLocation as SignInLocation
from office365.directory.audit.signins.status import SignInStatus as SignInStatus
from office365.directory.policies.applied_conditional_access import (
    AppliedConditionalAccessPolicy as AppliedConditionalAccessPolicy,
)
from office365.entity import Entity as Entity
from office365.intune.devices.detail import DeviceDetail as DeviceDetail
from office365.runtime.client_value_collection import (
    ClientValueCollection as ClientValueCollection,
)

class SignIn(Entity):
    @property
    def app_display_name(self) -> str | None: ...
    @property
    def app_id(self) -> str | None: ...
    @property
    def applied_conditional_access_policies(self) -> str | None: ...
    @property
    def client_app_used(self) -> str | None: ...
    @property
    def correlation_id(self) -> str | None: ...
    @property
    def created_datetime(self): ...
    @property
    def device_detail(self): ...
    @property
    def ip_address(self) -> str | None: ...
    @property
    def is_interactive(self) -> bool | None: ...
    @property
    def location(self): ...
    @property
    def resource_display_name(self) -> str | None: ...
    @property
    def resource_id(self) -> str | None: ...
    @property
    def risk_detail(self) -> str | None: ...
    @property
    def user_id(self) -> str | None: ...
    @property
    def user_principal_name(self) -> str | None: ...
    @property
    def status(self) -> SignInStatus | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
