import datetime
from office365.sharepoint.entity import Entity as Entity

class InformationRightsManagementSettings(Entity):
    @property
    def allow_print(self) -> bool | None: ...
    @property
    def allow_script(self) -> bool | None: ...
    @property
    def allow_write_copy(self) -> bool | None: ...
    @property
    def disable_document_browser_view(self) -> bool | None: ...
    @property
    def document_access_expire_days(self) -> int | None: ...
    @property
    def document_library_protection_expire_date(self) -> datetime.datetime | None: ...
    @property
    def enable_document_access_expire(self) -> bool | None: ...
    @property
    def enable_group_protection(self) -> bool | None: ...
    @property
    def enable_license_cache_expire(self) -> int | None: ...
    @property
    def policy_title(self) -> str | None: ...
    @property
    def policy_description(self) -> str | None: ...
    @property
    def group_name(self) -> str | None: ...
    @property
    def license_cache_expire_days(self) -> int | None: ...
    @property
    def template_id(self) -> str | None: ...
