import datetime
from typing import IO, AnyStr

from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.runtime.client_result import ClientResult as ClientResult
from office365.runtime.queries.function import FunctionQuery as FunctionQuery
from typing_extensions import Self

class Attachment(Entity):
    def download(self, file_object: IO) -> Self: ...
    def get_content(self) -> ClientResult[AnyStr]: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def content_type(self) -> str | None: ...
    @content_type.setter
    def content_type(self, value: str) -> None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def last_modified_datetime(self) -> datetime.datetime | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
