from _typeshed import Incomplete
from office365.entity import Entity as Entity
from office365.onedrive.idle_session_signout import (
    IdleSessionSignOut as IdleSessionSignOut,
)
from office365.runtime.types.collections import StringCollection as StringCollection

class SharepointSettings(Entity):
    @property
    def allowed_domain_guids_for_sync_app(self): ...
    @property
    def available_managed_paths_for_site_creation(self): ...
    @property
    def excluded_file_extensions_for_sync_app(self): ...
    @property
    def idle_session_sign_out(self) -> IdleSessionSignOut: ...
    @property
    def is_commenting_on_site_pages_enabled(self) -> bool | None: ...
    @property
    def sharing_allowed_domain_list(self) -> StringCollection: ...
    @property
    def sharing_blocked_domain_list(self) -> StringCollection: ...
    @sharing_blocked_domain_list.setter
    def sharing_blocked_domain_list(self, value: list[str]) -> None: ...
    @property
    def sharing_capability(self) -> str | None: ...
    @property
    def sharing_domain_restriction_mode(self) -> str | None: ...
    @property
    def site_creation_default_managed_path(self) -> str | None: ...
    @property
    def site_creation_default_storage_limit_in_mb(self) -> int | None: ...
    @property
    def tenant_default_timezone(self) -> str | None: ...
    @property
    def entity_type_name(self) -> None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
