from typing import Iterator

class ResourcePath:
    def __init__(self, key: int | str = None, parent: ResourcePath = None) -> None: ...
    def patch(self, key): ...
    def __iter__(self) -> Iterator['ResourcePath']: ...
    def __eq__(self, other): ...
    def to_url(self) -> str: ...
    @property
    def parent(self): ...
    @property
    def segment(self): ...
    @property
    def delimiter(self): ...
