from office365.runtime.client_runtime_context import ClientRuntimeContext as ClientRuntimeContext

class ExcelService(ClientRuntimeContext):
    def __init__(self, context) -> None: ...
    def authenticate_request(self, request) -> None: ...
    def service_root_url(self): ...
    def pending_request(self) -> None: ...
    def get_workbook(self, list_name, file_name) -> None: ...
