from _typeshed import Incomplete
from office365.onedrive.base_item import BaseItem as BaseItem
from office365.onedrive.columns.boolean import BooleanColumn as BooleanColumn
from office365.onedrive.columns.calculated import CalculatedColumn as CalculatedColumn
from office365.onedrive.columns.choice import ChoiceColumn as ChoiceColumn
from office365.onedrive.columns.content_approval_status import ContentApprovalStatusColumn as ContentApprovalStatusColumn
from office365.onedrive.columns.currency import CurrencyColumn as CurrencyColumn
from office365.onedrive.columns.datetime import DateTimeColumn as DateTimeColumn
from office365.onedrive.columns.default_value import DefaultColumnValue as DefaultColumnValue
from office365.onedrive.columns.geolocation import GeolocationColumn as GeolocationColumn
from office365.onedrive.columns.hyperlink_or_picture import HyperlinkOrPictureColumn as HyperlinkOrPictureColumn
from office365.onedrive.columns.lookup import LookupColumn as LookupColumn
from office365.onedrive.columns.number import NumberColumn as NumberColumn
from office365.onedrive.columns.person_or_group import PersonOrGroupColumn as PersonOrGroupColumn
from office365.onedrive.columns.term import TermColumn as TermColumn
from office365.onedrive.columns.text import TextColumn as TextColumn
from office365.onedrive.columns.thumbnail import ThumbnailColumn as ThumbnailColumn
from office365.onedrive.columns.validation import ColumnValidation as ColumnValidation
from office365.onedrive.contenttypes.info import ContentTypeInfo as ContentTypeInfo
from office365.runtime.paths.resource_path import ResourcePath as ResourcePath

class ColumnDefinition(BaseItem):
    @property
    def display_name(self) -> str | None: ...
    @property
    def enforce_unique_values(self) -> bool | None: ...
    @property
    def indexed(self) -> bool | None: ...
    @property
    def content_approval_status(self): ...
    @property
    def column_group(self) -> str | None: ...
    @property
    def boolean(self): ...
    @property
    def geolocation(self): ...
    @property
    def calculated(self): ...
    @property
    def choice(self): ...
    @property
    def currency(self): ...
    @property
    def datetime(self): ...
    @property
    def person_or_group(self): ...
    @property
    def text(self): ...
    @property
    def validation(self): ...
    @property
    def number(self): ...
    @property
    def lookup(self): ...
    @property
    def default_value(self): ...
    @property
    def hyperlink_or_picture(self): ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def is_deletable(self) -> bool | None: ...
    @property
    def is_reorderable(self) -> bool | None: ...
    @property
    def is_sealed(self) -> bool | None: ...
    @property
    def propagate_changes(self) -> bool | None: ...
    @property
    def read_only(self) -> bool | None: ...
    @property
    def thumbnail(self): ...
    @property
    def source_column(self) -> ColumnDefinition: ...
    @property
    def source_content_type(self): ...
    @property
    def term(self): ...
    @property
    def type(self) -> str | None: ...
    def get_property(self, name, default_value: Incomplete | None = None): ...
