# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code formatting with Black
        run: black --check --diff .

      - name: Lint with flake8
        run: flake8 .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    env:
      SKIP_AUTH: "true"
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML coverage report
        run: |
          pytest --cov=app --cov=routes --cov=utils --cov-report=html:htmlcov --cov-fail-under=80

      - name: Verify coverage report exists
        run: ls htmlcov || echo "Coverage report not generated"

      - name: Debug coverage report directory
        run: ls -al htmlcov/

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/
