# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      SKIP_AUTH: "true"
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML coverage report
        run: |
          pytest --cov=app --cov=routes --cov=utils --cov-report=html:htmlcov --cov-fail-under=80

      - name: Verify coverage report exists
        run: ls htmlcov || echo "Coverage report not generated"

      - name: Debug coverage report directory
        run: ls -al htmlcov/

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/
